// Code generated by ent, DO NOT EDIT.

package exclusivesubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldGroupID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldPlanID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldAccountID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldStatus, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldExpiresAt, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldAssignedAt, v))
}

// LastRenewalAt applies equality check predicate on the "last_renewal_at" field. It's identical to LastRenewalAtEQ.
func LastRenewalAt(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldLastRenewalAt, v))
}

// UsageUsd applies equality check predicate on the "usage_usd" field. It's identical to UsageUsdEQ.
func UsageUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldUsageUsd, v))
}

// DailyWindowStart applies equality check predicate on the "daily_window_start" field. It's identical to DailyWindowStartEQ.
func DailyWindowStart(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDailyWindowStart, v))
}

// WeeklyWindowStart applies equality check predicate on the "weekly_window_start" field. It's identical to WeeklyWindowStartEQ.
func WeeklyWindowStart(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// MonthlyWindowStart applies equality check predicate on the "monthly_window_start" field. It's identical to MonthlyWindowStartEQ.
func MonthlyWindowStart(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// DailyUsageUsd applies equality check predicate on the "daily_usage_usd" field. It's identical to DailyUsageUsdEQ.
func DailyUsageUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsd applies equality check predicate on the "weekly_usage_usd" field. It's identical to WeeklyUsageUsdEQ.
func WeeklyUsageUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsd applies equality check predicate on the "monthly_usage_usd" field. It's identical to MonthlyUsageUsdEQ.
func MonthlyUsageUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldNotes, v))
}

// AssignedBy applies equality check predicate on the "assigned_by" field. It's identical to AssignedByEQ.
func AssignedBy(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldAssignedBy, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldSourceOrderID, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// WeeklyLimitUsd applies equality check predicate on the "weekly_limit_usd" field. It's identical to WeeklyLimitUsdEQ.
func WeeklyLimitUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// MonthlyLimitUsd applies equality check predicate on the "monthly_limit_usd" field. It's identical to MonthlyLimitUsdEQ.
func MonthlyLimitUsd(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldRateMultiplier, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldGroupID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldPlanID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldAccountID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldContainsFold(FieldStatus, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldExpiresAt, v))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldAssignedAt, v))
}

// LastRenewalAtEQ applies the EQ predicate on the "last_renewal_at" field.
func LastRenewalAtEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldLastRenewalAt, v))
}

// LastRenewalAtNEQ applies the NEQ predicate on the "last_renewal_at" field.
func LastRenewalAtNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldLastRenewalAt, v))
}

// LastRenewalAtIn applies the In predicate on the "last_renewal_at" field.
func LastRenewalAtIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldLastRenewalAt, vs...))
}

// LastRenewalAtNotIn applies the NotIn predicate on the "last_renewal_at" field.
func LastRenewalAtNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldLastRenewalAt, vs...))
}

// LastRenewalAtGT applies the GT predicate on the "last_renewal_at" field.
func LastRenewalAtGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldLastRenewalAt, v))
}

// LastRenewalAtGTE applies the GTE predicate on the "last_renewal_at" field.
func LastRenewalAtGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldLastRenewalAt, v))
}

// LastRenewalAtLT applies the LT predicate on the "last_renewal_at" field.
func LastRenewalAtLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldLastRenewalAt, v))
}

// LastRenewalAtLTE applies the LTE predicate on the "last_renewal_at" field.
func LastRenewalAtLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldLastRenewalAt, v))
}

// LastRenewalAtIsNil applies the IsNil predicate on the "last_renewal_at" field.
func LastRenewalAtIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldLastRenewalAt))
}

// LastRenewalAtNotNil applies the NotNil predicate on the "last_renewal_at" field.
func LastRenewalAtNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldLastRenewalAt))
}

// UsageUsdEQ applies the EQ predicate on the "usage_usd" field.
func UsageUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldUsageUsd, v))
}

// UsageUsdNEQ applies the NEQ predicate on the "usage_usd" field.
func UsageUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldUsageUsd, v))
}

// UsageUsdIn applies the In predicate on the "usage_usd" field.
func UsageUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldUsageUsd, vs...))
}

// UsageUsdNotIn applies the NotIn predicate on the "usage_usd" field.
func UsageUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldUsageUsd, vs...))
}

// UsageUsdGT applies the GT predicate on the "usage_usd" field.
func UsageUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldUsageUsd, v))
}

// UsageUsdGTE applies the GTE predicate on the "usage_usd" field.
func UsageUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldUsageUsd, v))
}

// UsageUsdLT applies the LT predicate on the "usage_usd" field.
func UsageUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldUsageUsd, v))
}

// UsageUsdLTE applies the LTE predicate on the "usage_usd" field.
func UsageUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldUsageUsd, v))
}

// DailyWindowStartEQ applies the EQ predicate on the "daily_window_start" field.
func DailyWindowStartEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartNEQ applies the NEQ predicate on the "daily_window_start" field.
func DailyWindowStartNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartIn applies the In predicate on the "daily_window_start" field.
func DailyWindowStartIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartNotIn applies the NotIn predicate on the "daily_window_start" field.
func DailyWindowStartNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartGT applies the GT predicate on the "daily_window_start" field.
func DailyWindowStartGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldDailyWindowStart, v))
}

// DailyWindowStartGTE applies the GTE predicate on the "daily_window_start" field.
func DailyWindowStartGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldDailyWindowStart, v))
}

// DailyWindowStartLT applies the LT predicate on the "daily_window_start" field.
func DailyWindowStartLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldDailyWindowStart, v))
}

// DailyWindowStartLTE applies the LTE predicate on the "daily_window_start" field.
func DailyWindowStartLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldDailyWindowStart, v))
}

// DailyWindowStartIsNil applies the IsNil predicate on the "daily_window_start" field.
func DailyWindowStartIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldDailyWindowStart))
}

// DailyWindowStartNotNil applies the NotNil predicate on the "daily_window_start" field.
func DailyWindowStartNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldDailyWindowStart))
}

// WeeklyWindowStartEQ applies the EQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartNEQ applies the NEQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIn applies the In predicate on the "weekly_window_start" field.
func WeeklyWindowStartIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartNotIn applies the NotIn predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartGT applies the GT predicate on the "weekly_window_start" field.
func WeeklyWindowStartGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartGTE applies the GTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLT applies the LT predicate on the "weekly_window_start" field.
func WeeklyWindowStartLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLTE applies the LTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIsNil applies the IsNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldWeeklyWindowStart))
}

// WeeklyWindowStartNotNil applies the NotNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldWeeklyWindowStart))
}

// MonthlyWindowStartEQ applies the EQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartNEQ applies the NEQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartNEQ(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIn applies the In predicate on the "monthly_window_start" field.
func MonthlyWindowStartIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartNotIn applies the NotIn predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotIn(vs ...time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartGT applies the GT predicate on the "monthly_window_start" field.
func MonthlyWindowStartGT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartGTE applies the GTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartGTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLT applies the LT predicate on the "monthly_window_start" field.
func MonthlyWindowStartLT(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLTE applies the LTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartLTE(v time.Time) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIsNil applies the IsNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldMonthlyWindowStart))
}

// MonthlyWindowStartNotNil applies the NotNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldMonthlyWindowStart))
}

// DailyUsageUsdEQ applies the EQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdNEQ applies the NEQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdIn applies the In predicate on the "daily_usage_usd" field.
func DailyUsageUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdNotIn applies the NotIn predicate on the "daily_usage_usd" field.
func DailyUsageUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdGT applies the GT predicate on the "daily_usage_usd" field.
func DailyUsageUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdGTE applies the GTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLT applies the LT predicate on the "daily_usage_usd" field.
func DailyUsageUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLTE applies the LTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsdEQ applies the EQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdNEQ applies the NEQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdIn applies the In predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdNotIn applies the NotIn predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdGT applies the GT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdGTE applies the GTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLT applies the LT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLTE applies the LTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsdEQ applies the EQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdNEQ applies the NEQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdIn applies the In predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdNotIn applies the NotIn predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdGT applies the GT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdGTE applies the GTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLT applies the LT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLTE applies the LTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldMonthlyUsageUsd, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldContainsFold(FieldNotes, v))
}

// AssignedByEQ applies the EQ predicate on the "assigned_by" field.
func AssignedByEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldAssignedBy, v))
}

// AssignedByNEQ applies the NEQ predicate on the "assigned_by" field.
func AssignedByNEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldAssignedBy, v))
}

// AssignedByIn applies the In predicate on the "assigned_by" field.
func AssignedByIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldAssignedBy, vs...))
}

// AssignedByNotIn applies the NotIn predicate on the "assigned_by" field.
func AssignedByNotIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldAssignedBy, vs...))
}

// AssignedByGT applies the GT predicate on the "assigned_by" field.
func AssignedByGT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldAssignedBy, v))
}

// AssignedByGTE applies the GTE predicate on the "assigned_by" field.
func AssignedByGTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldAssignedBy, v))
}

// AssignedByLT applies the LT predicate on the "assigned_by" field.
func AssignedByLT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldAssignedBy, v))
}

// AssignedByLTE applies the LTE predicate on the "assigned_by" field.
func AssignedByLTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldAssignedBy, v))
}

// AssignedByIsNil applies the IsNil predicate on the "assigned_by" field.
func AssignedByIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldAssignedBy))
}

// AssignedByNotNil applies the NotNil predicate on the "assigned_by" field.
func AssignedByNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldAssignedBy))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDGT applies the GT predicate on the "source_order_id" field.
func SourceOrderIDGT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldSourceOrderID, v))
}

// SourceOrderIDGTE applies the GTE predicate on the "source_order_id" field.
func SourceOrderIDGTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldSourceOrderID, v))
}

// SourceOrderIDLT applies the LT predicate on the "source_order_id" field.
func SourceOrderIDLT(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldSourceOrderID, v))
}

// SourceOrderIDLTE applies the LTE predicate on the "source_order_id" field.
func SourceOrderIDLTE(v int64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldSourceOrderID, v))
}

// SourceOrderIDIsNil applies the IsNil predicate on the "source_order_id" field.
func SourceOrderIDIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldSourceOrderID))
}

// SourceOrderIDNotNil applies the NotNil predicate on the "source_order_id" field.
func SourceOrderIDNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldSourceOrderID))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIsNil applies the IsNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldDailyLimitUsd))
}

// DailyLimitUsdNotNil applies the NotNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldDailyLimitUsd))
}

// WeeklyLimitUsdEQ applies the EQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdNEQ applies the NEQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIn applies the In predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdNotIn applies the NotIn predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdGT applies the GT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdGTE applies the GTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLT applies the LT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLTE applies the LTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIsNil applies the IsNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldWeeklyLimitUsd))
}

// WeeklyLimitUsdNotNil applies the NotNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldWeeklyLimitUsd))
}

// MonthlyLimitUsdEQ applies the EQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdNEQ applies the NEQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIn applies the In predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdNotIn applies the NotIn predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdGT applies the GT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdGTE applies the GTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLT applies the LT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLTE applies the LTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIsNil applies the IsNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldMonthlyLimitUsd))
}

// MonthlyLimitUsdNotNil applies the NotNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldMonthlyLimitUsd))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldLTE(FieldRateMultiplier, v))
}

// RateMultiplierIsNil applies the IsNil predicate on the "rate_multiplier" field.
func RateMultiplierIsNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldIsNull(FieldRateMultiplier))
}

// RateMultiplierNotNil applies the NotNil predicate on the "rate_multiplier" field.
func RateMultiplierNotNil() predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.FieldNotNull(FieldRateMultiplier))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExclusiveSubscription) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExclusiveSubscription) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExclusiveSubscription) predicate.ExclusiveSubscription {
	return predicate.ExclusiveSubscription(sql.NotPredicates(p))
}
