// Code generated by ent, DO NOT EDIT.

package desktoprelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the desktoprelease type in the database.
	Label = "desktop_release"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldMandatory holds the string denoting the mandatory field in the database.
	FieldMandatory = "mandatory"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldSetupFile holds the string denoting the setup_file field in the database.
	FieldSetupFile = "setup_file"
	// FieldBlockmapFile holds the string denoting the blockmap_file field in the database.
	FieldBlockmapFile = "blockmap_file"
	// FieldLatestYml holds the string denoting the latest_yml field in the database.
	FieldLatestYml = "latest_yml"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the desktoprelease in the database.
	Table = "desktop_releases"
)

// Columns holds all SQL columns for desktoprelease fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldChannel,
	FieldMandatory,
	FieldNotes,
	FieldSetupFile,
	FieldBlockmapFile,
	FieldLatestYml,
	FieldFileSize,
	FieldStatus,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultChannel holds the default value on creation for the "channel" field.
	DefaultChannel string
	// ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	ChannelValidator func(string) error
	// DefaultMandatory holds the default value on creation for the "mandatory" field.
	DefaultMandatory bool
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// SetupFileValidator is a validator for the "setup_file" field. It is called by the builders before save.
	SetupFileValidator func(string) error
	// DefaultBlockmapFile holds the default value on creation for the "blockmap_file" field.
	DefaultBlockmapFile string
	// BlockmapFileValidator is a validator for the "blockmap_file" field. It is called by the builders before save.
	BlockmapFileValidator func(string) error
	// DefaultLatestYml holds the default value on creation for the "latest_yml" field.
	DefaultLatestYml string
	// DefaultFileSize holds the default value on creation for the "file_size" field.
	DefaultFileSize int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DesktopRelease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByMandatory orders the results by the mandatory field.
func ByMandatory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMandatory, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// BySetupFile orders the results by the setup_file field.
func BySetupFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSetupFile, opts...).ToFunc()
}

// ByBlockmapFile orders the results by the blockmap_file field.
func ByBlockmapFile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockmapFile, opts...).ToFunc()
}

// ByLatestYml orders the results by the latest_yml field.
func ByLatestYml(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestYml, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
