// Code generated by ent, DO NOT EDIT.

package desktoprelease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldVersion, v))
}

// Channel applies equality check predicate on the "channel" field. It's identical to ChannelEQ.
func Channel(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldChannel, v))
}

// Mandatory applies equality check predicate on the "mandatory" field. It's identical to MandatoryEQ.
func Mandatory(v bool) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldMandatory, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldNotes, v))
}

// SetupFile applies equality check predicate on the "setup_file" field. It's identical to SetupFileEQ.
func SetupFile(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldSetupFile, v))
}

// BlockmapFile applies equality check predicate on the "blockmap_file" field. It's identical to BlockmapFileEQ.
func BlockmapFile(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldBlockmapFile, v))
}

// LatestYml applies equality check predicate on the "latest_yml" field. It's identical to LatestYmlEQ.
func LatestYml(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldLatestYml, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldFileSize, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldStatus, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldUpdatedAt, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldVersion, v))
}

// ChannelEQ applies the EQ predicate on the "channel" field.
func ChannelEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldChannel, v))
}

// ChannelNEQ applies the NEQ predicate on the "channel" field.
func ChannelNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldChannel, v))
}

// ChannelIn applies the In predicate on the "channel" field.
func ChannelIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldChannel, vs...))
}

// ChannelNotIn applies the NotIn predicate on the "channel" field.
func ChannelNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldChannel, vs...))
}

// ChannelGT applies the GT predicate on the "channel" field.
func ChannelGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldChannel, v))
}

// ChannelGTE applies the GTE predicate on the "channel" field.
func ChannelGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldChannel, v))
}

// ChannelLT applies the LT predicate on the "channel" field.
func ChannelLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldChannel, v))
}

// ChannelLTE applies the LTE predicate on the "channel" field.
func ChannelLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldChannel, v))
}

// ChannelContains applies the Contains predicate on the "channel" field.
func ChannelContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldChannel, v))
}

// ChannelHasPrefix applies the HasPrefix predicate on the "channel" field.
func ChannelHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldChannel, v))
}

// ChannelHasSuffix applies the HasSuffix predicate on the "channel" field.
func ChannelHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldChannel, v))
}

// ChannelEqualFold applies the EqualFold predicate on the "channel" field.
func ChannelEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldChannel, v))
}

// ChannelContainsFold applies the ContainsFold predicate on the "channel" field.
func ChannelContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldChannel, v))
}

// MandatoryEQ applies the EQ predicate on the "mandatory" field.
func MandatoryEQ(v bool) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldMandatory, v))
}

// MandatoryNEQ applies the NEQ predicate on the "mandatory" field.
func MandatoryNEQ(v bool) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldMandatory, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldNotes, v))
}

// SetupFileEQ applies the EQ predicate on the "setup_file" field.
func SetupFileEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldSetupFile, v))
}

// SetupFileNEQ applies the NEQ predicate on the "setup_file" field.
func SetupFileNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldSetupFile, v))
}

// SetupFileIn applies the In predicate on the "setup_file" field.
func SetupFileIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldSetupFile, vs...))
}

// SetupFileNotIn applies the NotIn predicate on the "setup_file" field.
func SetupFileNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldSetupFile, vs...))
}

// SetupFileGT applies the GT predicate on the "setup_file" field.
func SetupFileGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldSetupFile, v))
}

// SetupFileGTE applies the GTE predicate on the "setup_file" field.
func SetupFileGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldSetupFile, v))
}

// SetupFileLT applies the LT predicate on the "setup_file" field.
func SetupFileLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldSetupFile, v))
}

// SetupFileLTE applies the LTE predicate on the "setup_file" field.
func SetupFileLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldSetupFile, v))
}

// SetupFileContains applies the Contains predicate on the "setup_file" field.
func SetupFileContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldSetupFile, v))
}

// SetupFileHasPrefix applies the HasPrefix predicate on the "setup_file" field.
func SetupFileHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldSetupFile, v))
}

// SetupFileHasSuffix applies the HasSuffix predicate on the "setup_file" field.
func SetupFileHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldSetupFile, v))
}

// SetupFileEqualFold applies the EqualFold predicate on the "setup_file" field.
func SetupFileEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldSetupFile, v))
}

// SetupFileContainsFold applies the ContainsFold predicate on the "setup_file" field.
func SetupFileContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldSetupFile, v))
}

// BlockmapFileEQ applies the EQ predicate on the "blockmap_file" field.
func BlockmapFileEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldBlockmapFile, v))
}

// BlockmapFileNEQ applies the NEQ predicate on the "blockmap_file" field.
func BlockmapFileNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldBlockmapFile, v))
}

// BlockmapFileIn applies the In predicate on the "blockmap_file" field.
func BlockmapFileIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldBlockmapFile, vs...))
}

// BlockmapFileNotIn applies the NotIn predicate on the "blockmap_file" field.
func BlockmapFileNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldBlockmapFile, vs...))
}

// BlockmapFileGT applies the GT predicate on the "blockmap_file" field.
func BlockmapFileGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldBlockmapFile, v))
}

// BlockmapFileGTE applies the GTE predicate on the "blockmap_file" field.
func BlockmapFileGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldBlockmapFile, v))
}

// BlockmapFileLT applies the LT predicate on the "blockmap_file" field.
func BlockmapFileLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldBlockmapFile, v))
}

// BlockmapFileLTE applies the LTE predicate on the "blockmap_file" field.
func BlockmapFileLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldBlockmapFile, v))
}

// BlockmapFileContains applies the Contains predicate on the "blockmap_file" field.
func BlockmapFileContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldBlockmapFile, v))
}

// BlockmapFileHasPrefix applies the HasPrefix predicate on the "blockmap_file" field.
func BlockmapFileHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldBlockmapFile, v))
}

// BlockmapFileHasSuffix applies the HasSuffix predicate on the "blockmap_file" field.
func BlockmapFileHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldBlockmapFile, v))
}

// BlockmapFileEqualFold applies the EqualFold predicate on the "blockmap_file" field.
func BlockmapFileEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldBlockmapFile, v))
}

// BlockmapFileContainsFold applies the ContainsFold predicate on the "blockmap_file" field.
func BlockmapFileContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldBlockmapFile, v))
}

// LatestYmlEQ applies the EQ predicate on the "latest_yml" field.
func LatestYmlEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldLatestYml, v))
}

// LatestYmlNEQ applies the NEQ predicate on the "latest_yml" field.
func LatestYmlNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldLatestYml, v))
}

// LatestYmlIn applies the In predicate on the "latest_yml" field.
func LatestYmlIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldLatestYml, vs...))
}

// LatestYmlNotIn applies the NotIn predicate on the "latest_yml" field.
func LatestYmlNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldLatestYml, vs...))
}

// LatestYmlGT applies the GT predicate on the "latest_yml" field.
func LatestYmlGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldLatestYml, v))
}

// LatestYmlGTE applies the GTE predicate on the "latest_yml" field.
func LatestYmlGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldLatestYml, v))
}

// LatestYmlLT applies the LT predicate on the "latest_yml" field.
func LatestYmlLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldLatestYml, v))
}

// LatestYmlLTE applies the LTE predicate on the "latest_yml" field.
func LatestYmlLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldLatestYml, v))
}

// LatestYmlContains applies the Contains predicate on the "latest_yml" field.
func LatestYmlContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldLatestYml, v))
}

// LatestYmlHasPrefix applies the HasPrefix predicate on the "latest_yml" field.
func LatestYmlHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldLatestYml, v))
}

// LatestYmlHasSuffix applies the HasSuffix predicate on the "latest_yml" field.
func LatestYmlHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldLatestYml, v))
}

// LatestYmlEqualFold applies the EqualFold predicate on the "latest_yml" field.
func LatestYmlEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldLatestYml, v))
}

// LatestYmlContainsFold applies the ContainsFold predicate on the "latest_yml" field.
func LatestYmlContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldLatestYml, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldFileSize, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DesktopRelease) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DesktopRelease) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DesktopRelease) predicate.DesktopRelease {
	return predicate.DesktopRelease(sql.NotPredicates(p))
}
