// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/desktoprelease"
)

// DesktopRelease is the model entity for the DesktopRelease schema.
type DesktopRelease struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 版本号，如 0.2.0
	Version string `json:"version,omitempty"`
	// 发布通道: stable, beta
	Channel string `json:"channel,omitempty"`
	// 是否强制更新（写入 release.json 供客户端弹不可跳过遮罩）
	Mandatory bool `json:"mandatory,omitempty"`
	// 更新说明（展示给用户）
	Notes string `json:"notes,omitempty"`
	// 安装包文件名（相对更新目录根，如 Velorix-0.2.0-setup.exe）
	SetupFile string `json:"setup_file,omitempty"`
	// blockmap 文件名（增量更新用，可空）
	BlockmapFile string `json:"blockmap_file,omitempty"`
	// electron-updater 的 latest.yml 全文内容
	LatestYml string `json:"latest_yml,omitempty"`
	// 安装包字节大小
	FileSize int64 `json:"file_size,omitempty"`
	// 状态: active(当前对外), archived(历史), rolledback(已回滚)
	Status string `json:"status,omitempty"`
	// 发布人用户ID（管理员）
	CreatedBy *int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopRelease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktoprelease.FieldMandatory:
			values[i] = new(sql.NullBool)
		case desktoprelease.FieldID, desktoprelease.FieldFileSize, desktoprelease.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case desktoprelease.FieldVersion, desktoprelease.FieldChannel, desktoprelease.FieldNotes, desktoprelease.FieldSetupFile, desktoprelease.FieldBlockmapFile, desktoprelease.FieldLatestYml, desktoprelease.FieldStatus:
			values[i] = new(sql.NullString)
		case desktoprelease.FieldCreatedAt, desktoprelease.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopRelease fields.
func (_m *DesktopRelease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktoprelease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktoprelease.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case desktoprelease.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = value.String
			}
		case desktoprelease.FieldMandatory:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mandatory", values[i])
			} else if value.Valid {
				_m.Mandatory = value.Bool
			}
		case desktoprelease.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case desktoprelease.FieldSetupFile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setup_file", values[i])
			} else if value.Valid {
				_m.SetupFile = value.String
			}
		case desktoprelease.FieldBlockmapFile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blockmap_file", values[i])
			} else if value.Valid {
				_m.BlockmapFile = value.String
			}
		case desktoprelease.FieldLatestYml:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field latest_yml", values[i])
			} else if value.Valid {
				_m.LatestYml = value.String
			}
		case desktoprelease.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case desktoprelease.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case desktoprelease.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case desktoprelease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case desktoprelease.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopRelease.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopRelease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DesktopRelease.
// Note that you need to call DesktopRelease.Unwrap() before calling this method if this DesktopRelease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopRelease) Update() *DesktopReleaseUpdateOne {
	return NewDesktopReleaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopRelease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopRelease) Unwrap() *DesktopRelease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopRelease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopRelease) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopRelease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(_m.Channel)
	builder.WriteString(", ")
	builder.WriteString("mandatory=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mandatory))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("setup_file=")
	builder.WriteString(_m.SetupFile)
	builder.WriteString(", ")
	builder.WriteString("blockmap_file=")
	builder.WriteString(_m.BlockmapFile)
	builder.WriteString(", ")
	builder.WriteString("latest_yml=")
	builder.WriteString(_m.LatestYml)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DesktopReleases is a parsable slice of DesktopRelease.
type DesktopReleases []*DesktopRelease
