// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktoprelease"
)

// DesktopReleaseCreate is the builder for creating a DesktopRelease entity.
type DesktopReleaseCreate struct {
	config
	mutation *DesktopReleaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVersion sets the "version" field.
func (_c *DesktopReleaseCreate) SetVersion(v string) *DesktopReleaseCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetChannel sets the "channel" field.
func (_c *DesktopReleaseCreate) SetChannel(v string) *DesktopReleaseCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableChannel(v *string) *DesktopReleaseCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// SetMandatory sets the "mandatory" field.
func (_c *DesktopReleaseCreate) SetMandatory(v bool) *DesktopReleaseCreate {
	_c.mutation.SetMandatory(v)
	return _c
}

// SetNillableMandatory sets the "mandatory" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableMandatory(v *bool) *DesktopReleaseCreate {
	if v != nil {
		_c.SetMandatory(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *DesktopReleaseCreate) SetNotes(v string) *DesktopReleaseCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableNotes(v *string) *DesktopReleaseCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetSetupFile sets the "setup_file" field.
func (_c *DesktopReleaseCreate) SetSetupFile(v string) *DesktopReleaseCreate {
	_c.mutation.SetSetupFile(v)
	return _c
}

// SetBlockmapFile sets the "blockmap_file" field.
func (_c *DesktopReleaseCreate) SetBlockmapFile(v string) *DesktopReleaseCreate {
	_c.mutation.SetBlockmapFile(v)
	return _c
}

// SetNillableBlockmapFile sets the "blockmap_file" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableBlockmapFile(v *string) *DesktopReleaseCreate {
	if v != nil {
		_c.SetBlockmapFile(*v)
	}
	return _c
}

// SetLatestYml sets the "latest_yml" field.
func (_c *DesktopReleaseCreate) SetLatestYml(v string) *DesktopReleaseCreate {
	_c.mutation.SetLatestYml(v)
	return _c
}

// SetNillableLatestYml sets the "latest_yml" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableLatestYml(v *string) *DesktopReleaseCreate {
	if v != nil {
		_c.SetLatestYml(*v)
	}
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *DesktopReleaseCreate) SetFileSize(v int64) *DesktopReleaseCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableFileSize(v *int64) *DesktopReleaseCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DesktopReleaseCreate) SetStatus(v string) *DesktopReleaseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableStatus(v *string) *DesktopReleaseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DesktopReleaseCreate) SetCreatedBy(v int64) *DesktopReleaseCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableCreatedBy(v *int64) *DesktopReleaseCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopReleaseCreate) SetCreatedAt(v time.Time) *DesktopReleaseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableCreatedAt(v *time.Time) *DesktopReleaseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopReleaseCreate) SetUpdatedAt(v time.Time) *DesktopReleaseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopReleaseCreate) SetNillableUpdatedAt(v *time.Time) *DesktopReleaseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DesktopReleaseMutation object of the builder.
func (_c *DesktopReleaseCreate) Mutation() *DesktopReleaseMutation {
	return _c.mutation
}

// Save creates the DesktopRelease in the database.
func (_c *DesktopReleaseCreate) Save(ctx context.Context) (*DesktopRelease, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopReleaseCreate) SaveX(ctx context.Context) *DesktopRelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopReleaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopReleaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopReleaseCreate) defaults() {
	if _, ok := _c.mutation.Channel(); !ok {
		v := desktoprelease.DefaultChannel
		_c.mutation.SetChannel(v)
	}
	if _, ok := _c.mutation.Mandatory(); !ok {
		v := desktoprelease.DefaultMandatory
		_c.mutation.SetMandatory(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := desktoprelease.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.BlockmapFile(); !ok {
		v := desktoprelease.DefaultBlockmapFile
		_c.mutation.SetBlockmapFile(v)
	}
	if _, ok := _c.mutation.LatestYml(); !ok {
		v := desktoprelease.DefaultLatestYml
		_c.mutation.SetLatestYml(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := desktoprelease.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := desktoprelease.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := desktoprelease.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := desktoprelease.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopReleaseCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "DesktopRelease.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := desktoprelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "DesktopRelease.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := desktoprelease.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mandatory(); !ok {
		return &ValidationError{Name: "mandatory", err: errors.New(`ent: missing required field "DesktopRelease.mandatory"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "DesktopRelease.notes"`)}
	}
	if _, ok := _c.mutation.SetupFile(); !ok {
		return &ValidationError{Name: "setup_file", err: errors.New(`ent: missing required field "DesktopRelease.setup_file"`)}
	}
	if v, ok := _c.mutation.SetupFile(); ok {
		if err := desktoprelease.SetupFileValidator(v); err != nil {
			return &ValidationError{Name: "setup_file", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.setup_file": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlockmapFile(); !ok {
		return &ValidationError{Name: "blockmap_file", err: errors.New(`ent: missing required field "DesktopRelease.blockmap_file"`)}
	}
	if v, ok := _c.mutation.BlockmapFile(); ok {
		if err := desktoprelease.BlockmapFileValidator(v); err != nil {
			return &ValidationError{Name: "blockmap_file", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.blockmap_file": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LatestYml(); !ok {
		return &ValidationError{Name: "latest_yml", err: errors.New(`ent: missing required field "DesktopRelease.latest_yml"`)}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "DesktopRelease.file_size"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DesktopRelease.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := desktoprelease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopRelease.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopRelease.updated_at"`)}
	}
	return nil
}

func (_c *DesktopReleaseCreate) sqlSave(ctx context.Context) (*DesktopRelease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopReleaseCreate) createSpec() (*DesktopRelease, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopRelease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktoprelease.Table, sqlgraph.NewFieldSpec(desktoprelease.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(desktoprelease.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(desktoprelease.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Mandatory(); ok {
		_spec.SetField(desktoprelease.FieldMandatory, field.TypeBool, value)
		_node.Mandatory = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(desktoprelease.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.SetupFile(); ok {
		_spec.SetField(desktoprelease.FieldSetupFile, field.TypeString, value)
		_node.SetupFile = value
	}
	if value, ok := _c.mutation.BlockmapFile(); ok {
		_spec.SetField(desktoprelease.FieldBlockmapFile, field.TypeString, value)
		_node.BlockmapFile = value
	}
	if value, ok := _c.mutation.LatestYml(); ok {
		_spec.SetField(desktoprelease.FieldLatestYml, field.TypeString, value)
		_node.LatestYml = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(desktoprelease.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(desktoprelease.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(desktoprelease.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktoprelease.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktoprelease.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopRelease.Create().
//		SetVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopReleaseUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopReleaseCreate) OnConflict(opts ...sql.ConflictOption) *DesktopReleaseUpsertOne {
	_c.conflict = opts
	return &DesktopReleaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopRelease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopReleaseCreate) OnConflictColumns(columns ...string) *DesktopReleaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopReleaseUpsertOne{
		create: _c,
	}
}

type (
	// DesktopReleaseUpsertOne is the builder for "upsert"-ing
	//  one DesktopRelease node.
	DesktopReleaseUpsertOne struct {
		create *DesktopReleaseCreate
	}

	// DesktopReleaseUpsert is the "OnConflict" setter.
	DesktopReleaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetVersion sets the "version" field.
func (u *DesktopReleaseUpsert) SetVersion(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateVersion() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldVersion)
	return u
}

// SetChannel sets the "channel" field.
func (u *DesktopReleaseUpsert) SetChannel(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldChannel, v)
	return u
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateChannel() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldChannel)
	return u
}

// SetMandatory sets the "mandatory" field.
func (u *DesktopReleaseUpsert) SetMandatory(v bool) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldMandatory, v)
	return u
}

// UpdateMandatory sets the "mandatory" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateMandatory() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldMandatory)
	return u
}

// SetNotes sets the "notes" field.
func (u *DesktopReleaseUpsert) SetNotes(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateNotes() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldNotes)
	return u
}

// SetSetupFile sets the "setup_file" field.
func (u *DesktopReleaseUpsert) SetSetupFile(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldSetupFile, v)
	return u
}

// UpdateSetupFile sets the "setup_file" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateSetupFile() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldSetupFile)
	return u
}

// SetBlockmapFile sets the "blockmap_file" field.
func (u *DesktopReleaseUpsert) SetBlockmapFile(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldBlockmapFile, v)
	return u
}

// UpdateBlockmapFile sets the "blockmap_file" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateBlockmapFile() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldBlockmapFile)
	return u
}

// SetLatestYml sets the "latest_yml" field.
func (u *DesktopReleaseUpsert) SetLatestYml(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldLatestYml, v)
	return u
}

// UpdateLatestYml sets the "latest_yml" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateLatestYml() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldLatestYml)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *DesktopReleaseUpsert) SetFileSize(v int64) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateFileSize() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *DesktopReleaseUpsert) AddFileSize(v int64) *DesktopReleaseUpsert {
	u.Add(desktoprelease.FieldFileSize, v)
	return u
}

// SetStatus sets the "status" field.
func (u *DesktopReleaseUpsert) SetStatus(v string) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateStatus() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *DesktopReleaseUpsert) SetCreatedBy(v int64) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateCreatedBy() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DesktopReleaseUpsert) AddCreatedBy(v int64) *DesktopReleaseUpsert {
	u.Add(desktoprelease.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DesktopReleaseUpsert) ClearCreatedBy() *DesktopReleaseUpsert {
	u.SetNull(desktoprelease.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopReleaseUpsert) SetUpdatedAt(v time.Time) *DesktopReleaseUpsert {
	u.Set(desktoprelease.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopReleaseUpsert) UpdateUpdatedAt() *DesktopReleaseUpsert {
	u.SetExcluded(desktoprelease.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopRelease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopReleaseUpsertOne) UpdateNewValues() *DesktopReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktoprelease.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopRelease.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopReleaseUpsertOne) Ignore() *DesktopReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopReleaseUpsertOne) DoNothing() *DesktopReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopReleaseCreate.OnConflict
// documentation for more info.
func (u *DesktopReleaseUpsertOne) Update(set func(*DesktopReleaseUpsert)) *DesktopReleaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopReleaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *DesktopReleaseUpsertOne) SetVersion(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateVersion() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateVersion()
	})
}

// SetChannel sets the "channel" field.
func (u *DesktopReleaseUpsertOne) SetChannel(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateChannel() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateChannel()
	})
}

// SetMandatory sets the "mandatory" field.
func (u *DesktopReleaseUpsertOne) SetMandatory(v bool) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetMandatory(v)
	})
}

// UpdateMandatory sets the "mandatory" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateMandatory() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateMandatory()
	})
}

// SetNotes sets the "notes" field.
func (u *DesktopReleaseUpsertOne) SetNotes(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateNotes() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateNotes()
	})
}

// SetSetupFile sets the "setup_file" field.
func (u *DesktopReleaseUpsertOne) SetSetupFile(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetSetupFile(v)
	})
}

// UpdateSetupFile sets the "setup_file" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateSetupFile() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateSetupFile()
	})
}

// SetBlockmapFile sets the "blockmap_file" field.
func (u *DesktopReleaseUpsertOne) SetBlockmapFile(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetBlockmapFile(v)
	})
}

// UpdateBlockmapFile sets the "blockmap_file" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateBlockmapFile() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateBlockmapFile()
	})
}

// SetLatestYml sets the "latest_yml" field.
func (u *DesktopReleaseUpsertOne) SetLatestYml(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetLatestYml(v)
	})
}

// UpdateLatestYml sets the "latest_yml" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateLatestYml() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateLatestYml()
	})
}

// SetFileSize sets the "file_size" field.
func (u *DesktopReleaseUpsertOne) SetFileSize(v int64) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *DesktopReleaseUpsertOne) AddFileSize(v int64) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateFileSize() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateFileSize()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopReleaseUpsertOne) SetStatus(v string) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateStatus() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DesktopReleaseUpsertOne) SetCreatedBy(v int64) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DesktopReleaseUpsertOne) AddCreatedBy(v int64) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateCreatedBy() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DesktopReleaseUpsertOne) ClearCreatedBy() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopReleaseUpsertOne) SetUpdatedAt(v time.Time) *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopReleaseUpsertOne) UpdateUpdatedAt() *DesktopReleaseUpsertOne {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DesktopReleaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopReleaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopReleaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopReleaseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopReleaseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopReleaseCreateBulk is the builder for creating many DesktopRelease entities in bulk.
type DesktopReleaseCreateBulk struct {
	config
	err      error
	builders []*DesktopReleaseCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopRelease entities in the database.
func (_c *DesktopReleaseCreateBulk) Save(ctx context.Context) ([]*DesktopRelease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopRelease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopReleaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopReleaseCreateBulk) SaveX(ctx context.Context) []*DesktopRelease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopReleaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopReleaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopRelease.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopReleaseUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopReleaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopReleaseUpsertBulk {
	_c.conflict = opts
	return &DesktopReleaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopRelease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopReleaseCreateBulk) OnConflictColumns(columns ...string) *DesktopReleaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopReleaseUpsertBulk{
		create: _c,
	}
}

// DesktopReleaseUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopRelease nodes.
type DesktopReleaseUpsertBulk struct {
	create *DesktopReleaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopRelease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopReleaseUpsertBulk) UpdateNewValues() *DesktopReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktoprelease.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopRelease.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopReleaseUpsertBulk) Ignore() *DesktopReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopReleaseUpsertBulk) DoNothing() *DesktopReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopReleaseCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopReleaseUpsertBulk) Update(set func(*DesktopReleaseUpsert)) *DesktopReleaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopReleaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *DesktopReleaseUpsertBulk) SetVersion(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateVersion() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateVersion()
	})
}

// SetChannel sets the "channel" field.
func (u *DesktopReleaseUpsertBulk) SetChannel(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetChannel(v)
	})
}

// UpdateChannel sets the "channel" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateChannel() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateChannel()
	})
}

// SetMandatory sets the "mandatory" field.
func (u *DesktopReleaseUpsertBulk) SetMandatory(v bool) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetMandatory(v)
	})
}

// UpdateMandatory sets the "mandatory" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateMandatory() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateMandatory()
	})
}

// SetNotes sets the "notes" field.
func (u *DesktopReleaseUpsertBulk) SetNotes(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateNotes() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateNotes()
	})
}

// SetSetupFile sets the "setup_file" field.
func (u *DesktopReleaseUpsertBulk) SetSetupFile(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetSetupFile(v)
	})
}

// UpdateSetupFile sets the "setup_file" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateSetupFile() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateSetupFile()
	})
}

// SetBlockmapFile sets the "blockmap_file" field.
func (u *DesktopReleaseUpsertBulk) SetBlockmapFile(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetBlockmapFile(v)
	})
}

// UpdateBlockmapFile sets the "blockmap_file" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateBlockmapFile() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateBlockmapFile()
	})
}

// SetLatestYml sets the "latest_yml" field.
func (u *DesktopReleaseUpsertBulk) SetLatestYml(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetLatestYml(v)
	})
}

// UpdateLatestYml sets the "latest_yml" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateLatestYml() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateLatestYml()
	})
}

// SetFileSize sets the "file_size" field.
func (u *DesktopReleaseUpsertBulk) SetFileSize(v int64) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *DesktopReleaseUpsertBulk) AddFileSize(v int64) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateFileSize() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateFileSize()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopReleaseUpsertBulk) SetStatus(v string) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateStatus() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DesktopReleaseUpsertBulk) SetCreatedBy(v int64) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DesktopReleaseUpsertBulk) AddCreatedBy(v int64) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateCreatedBy() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DesktopReleaseUpsertBulk) ClearCreatedBy() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopReleaseUpsertBulk) SetUpdatedAt(v time.Time) *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopReleaseUpsertBulk) UpdateUpdatedAt() *DesktopReleaseUpsertBulk {
	return u.Update(func(s *DesktopReleaseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DesktopReleaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopReleaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopReleaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopReleaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
