// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktoprelease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopReleaseUpdate is the builder for updating DesktopRelease entities.
type DesktopReleaseUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopReleaseMutation
}

// Where appends a list predicates to the DesktopReleaseUpdate builder.
func (_u *DesktopReleaseUpdate) Where(ps ...predicate.DesktopRelease) *DesktopReleaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *DesktopReleaseUpdate) SetVersion(v string) *DesktopReleaseUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableVersion(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *DesktopReleaseUpdate) SetChannel(v string) *DesktopReleaseUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableChannel(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetMandatory sets the "mandatory" field.
func (_u *DesktopReleaseUpdate) SetMandatory(v bool) *DesktopReleaseUpdate {
	_u.mutation.SetMandatory(v)
	return _u
}

// SetNillableMandatory sets the "mandatory" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableMandatory(v *bool) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetMandatory(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *DesktopReleaseUpdate) SetNotes(v string) *DesktopReleaseUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableNotes(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetSetupFile sets the "setup_file" field.
func (_u *DesktopReleaseUpdate) SetSetupFile(v string) *DesktopReleaseUpdate {
	_u.mutation.SetSetupFile(v)
	return _u
}

// SetNillableSetupFile sets the "setup_file" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableSetupFile(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetSetupFile(*v)
	}
	return _u
}

// SetBlockmapFile sets the "blockmap_file" field.
func (_u *DesktopReleaseUpdate) SetBlockmapFile(v string) *DesktopReleaseUpdate {
	_u.mutation.SetBlockmapFile(v)
	return _u
}

// SetNillableBlockmapFile sets the "blockmap_file" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableBlockmapFile(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetBlockmapFile(*v)
	}
	return _u
}

// SetLatestYml sets the "latest_yml" field.
func (_u *DesktopReleaseUpdate) SetLatestYml(v string) *DesktopReleaseUpdate {
	_u.mutation.SetLatestYml(v)
	return _u
}

// SetNillableLatestYml sets the "latest_yml" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableLatestYml(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetLatestYml(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *DesktopReleaseUpdate) SetFileSize(v int64) *DesktopReleaseUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableFileSize(v *int64) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *DesktopReleaseUpdate) AddFileSize(v int64) *DesktopReleaseUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopReleaseUpdate) SetStatus(v string) *DesktopReleaseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableStatus(v *string) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DesktopReleaseUpdate) SetCreatedBy(v int64) *DesktopReleaseUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DesktopReleaseUpdate) SetNillableCreatedBy(v *int64) *DesktopReleaseUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DesktopReleaseUpdate) AddCreatedBy(v int64) *DesktopReleaseUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DesktopReleaseUpdate) ClearCreatedBy() *DesktopReleaseUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopReleaseUpdate) SetUpdatedAt(v time.Time) *DesktopReleaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DesktopReleaseMutation object of the builder.
func (_u *DesktopReleaseUpdate) Mutation() *DesktopReleaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopReleaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopReleaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopReleaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopReleaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopReleaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktoprelease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopReleaseUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := desktoprelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := desktoprelease.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SetupFile(); ok {
		if err := desktoprelease.SetupFileValidator(v); err != nil {
			return &ValidationError{Name: "setup_file", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.setup_file": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockmapFile(); ok {
		if err := desktoprelease.BlockmapFileValidator(v); err != nil {
			return &ValidationError{Name: "blockmap_file", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.blockmap_file": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktoprelease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DesktopReleaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktoprelease.Table, desktoprelease.Columns, sqlgraph.NewFieldSpec(desktoprelease.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(desktoprelease.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(desktoprelease.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mandatory(); ok {
		_spec.SetField(desktoprelease.FieldMandatory, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(desktoprelease.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetupFile(); ok {
		_spec.SetField(desktoprelease.FieldSetupFile, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlockmapFile(); ok {
		_spec.SetField(desktoprelease.FieldBlockmapFile, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatestYml(); ok {
		_spec.SetField(desktoprelease.FieldLatestYml, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(desktoprelease.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(desktoprelease.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktoprelease.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(desktoprelease.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(desktoprelease.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(desktoprelease.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktoprelease.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktoprelease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopReleaseUpdateOne is the builder for updating a single DesktopRelease entity.
type DesktopReleaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopReleaseMutation
}

// SetVersion sets the "version" field.
func (_u *DesktopReleaseUpdateOne) SetVersion(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableVersion(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *DesktopReleaseUpdateOne) SetChannel(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableChannel(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetMandatory sets the "mandatory" field.
func (_u *DesktopReleaseUpdateOne) SetMandatory(v bool) *DesktopReleaseUpdateOne {
	_u.mutation.SetMandatory(v)
	return _u
}

// SetNillableMandatory sets the "mandatory" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableMandatory(v *bool) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetMandatory(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *DesktopReleaseUpdateOne) SetNotes(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableNotes(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetSetupFile sets the "setup_file" field.
func (_u *DesktopReleaseUpdateOne) SetSetupFile(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetSetupFile(v)
	return _u
}

// SetNillableSetupFile sets the "setup_file" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableSetupFile(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetSetupFile(*v)
	}
	return _u
}

// SetBlockmapFile sets the "blockmap_file" field.
func (_u *DesktopReleaseUpdateOne) SetBlockmapFile(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetBlockmapFile(v)
	return _u
}

// SetNillableBlockmapFile sets the "blockmap_file" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableBlockmapFile(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetBlockmapFile(*v)
	}
	return _u
}

// SetLatestYml sets the "latest_yml" field.
func (_u *DesktopReleaseUpdateOne) SetLatestYml(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetLatestYml(v)
	return _u
}

// SetNillableLatestYml sets the "latest_yml" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableLatestYml(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetLatestYml(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *DesktopReleaseUpdateOne) SetFileSize(v int64) *DesktopReleaseUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableFileSize(v *int64) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *DesktopReleaseUpdateOne) AddFileSize(v int64) *DesktopReleaseUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopReleaseUpdateOne) SetStatus(v string) *DesktopReleaseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableStatus(v *string) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DesktopReleaseUpdateOne) SetCreatedBy(v int64) *DesktopReleaseUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DesktopReleaseUpdateOne) SetNillableCreatedBy(v *int64) *DesktopReleaseUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DesktopReleaseUpdateOne) AddCreatedBy(v int64) *DesktopReleaseUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DesktopReleaseUpdateOne) ClearCreatedBy() *DesktopReleaseUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopReleaseUpdateOne) SetUpdatedAt(v time.Time) *DesktopReleaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DesktopReleaseMutation object of the builder.
func (_u *DesktopReleaseUpdateOne) Mutation() *DesktopReleaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the DesktopReleaseUpdate builder.
func (_u *DesktopReleaseUpdateOne) Where(ps ...predicate.DesktopRelease) *DesktopReleaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopReleaseUpdateOne) Select(field string, fields ...string) *DesktopReleaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopRelease entity.
func (_u *DesktopReleaseUpdateOne) Save(ctx context.Context) (*DesktopRelease, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopReleaseUpdateOne) SaveX(ctx context.Context) *DesktopRelease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopReleaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopReleaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopReleaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktoprelease.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopReleaseUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := desktoprelease.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := desktoprelease.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SetupFile(); ok {
		if err := desktoprelease.SetupFileValidator(v); err != nil {
			return &ValidationError{Name: "setup_file", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.setup_file": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockmapFile(); ok {
		if err := desktoprelease.BlockmapFileValidator(v); err != nil {
			return &ValidationError{Name: "blockmap_file", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.blockmap_file": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktoprelease.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopRelease.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DesktopReleaseUpdateOne) sqlSave(ctx context.Context) (_node *DesktopRelease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktoprelease.Table, desktoprelease.Columns, sqlgraph.NewFieldSpec(desktoprelease.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopRelease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktoprelease.FieldID)
		for _, f := range fields {
			if !desktoprelease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktoprelease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(desktoprelease.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(desktoprelease.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mandatory(); ok {
		_spec.SetField(desktoprelease.FieldMandatory, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(desktoprelease.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SetupFile(); ok {
		_spec.SetField(desktoprelease.FieldSetupFile, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlockmapFile(); ok {
		_spec.SetField(desktoprelease.FieldBlockmapFile, field.TypeString, value)
	}
	if value, ok := _u.mutation.LatestYml(); ok {
		_spec.SetField(desktoprelease.FieldLatestYml, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(desktoprelease.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(desktoprelease.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktoprelease.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(desktoprelease.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(desktoprelease.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(desktoprelease.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktoprelease.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DesktopRelease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktoprelease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
