// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktoprelease"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopReleaseDelete is the builder for deleting a DesktopRelease entity.
type DesktopReleaseDelete struct {
	config
	hooks    []Hook
	mutation *DesktopReleaseMutation
}

// Where appends a list predicates to the DesktopReleaseDelete builder.
func (_d *DesktopReleaseDelete) Where(ps ...predicate.DesktopRelease) *DesktopReleaseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DesktopReleaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DesktopReleaseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DesktopReleaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(desktoprelease.Table, sqlgraph.NewFieldSpec(desktoprelease.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DesktopReleaseDeleteOne is the builder for deleting a single DesktopRelease entity.
type DesktopReleaseDeleteOne struct {
	_d *DesktopReleaseDelete
}

// Where appends a list predicates to the DesktopReleaseDelete builder.
func (_d *DesktopReleaseDeleteOne) Where(ps ...predicate.DesktopRelease) *DesktopReleaseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DesktopReleaseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{desktoprelease.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DesktopReleaseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
