// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/exclusivesubscription"
)

// ExclusiveSubscription is the model entity for the ExclusiveSubscription schema.
type ExclusiveSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID int64 `json:"plan_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// LastRenewalAt holds the value of the "last_renewal_at" field.
	LastRenewalAt *time.Time `json:"last_renewal_at,omitempty"`
	// UsageUsd holds the value of the "usage_usd" field.
	UsageUsd float64 `json:"usage_usd,omitempty"`
	// DailyWindowStart holds the value of the "daily_window_start" field.
	DailyWindowStart *time.Time `json:"daily_window_start,omitempty"`
	// WeeklyWindowStart holds the value of the "weekly_window_start" field.
	WeeklyWindowStart *time.Time `json:"weekly_window_start,omitempty"`
	// MonthlyWindowStart holds the value of the "monthly_window_start" field.
	MonthlyWindowStart *time.Time `json:"monthly_window_start,omitempty"`
	// DailyUsageUsd holds the value of the "daily_usage_usd" field.
	DailyUsageUsd float64 `json:"daily_usage_usd,omitempty"`
	// WeeklyUsageUsd holds the value of the "weekly_usage_usd" field.
	WeeklyUsageUsd float64 `json:"weekly_usage_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// AssignedBy holds the value of the "assigned_by" field.
	AssignedBy *int64 `json:"assigned_by,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID *int64 `json:"source_order_id,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd *float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier *float64 `json:"rate_multiplier,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExclusiveSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exclusivesubscription.FieldUsageUsd, exclusivesubscription.FieldDailyUsageUsd, exclusivesubscription.FieldWeeklyUsageUsd, exclusivesubscription.FieldMonthlyUsageUsd, exclusivesubscription.FieldDailyLimitUsd, exclusivesubscription.FieldWeeklyLimitUsd, exclusivesubscription.FieldMonthlyLimitUsd, exclusivesubscription.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case exclusivesubscription.FieldID, exclusivesubscription.FieldUserID, exclusivesubscription.FieldGroupID, exclusivesubscription.FieldPlanID, exclusivesubscription.FieldAccountID, exclusivesubscription.FieldAssignedBy, exclusivesubscription.FieldSourceOrderID:
			values[i] = new(sql.NullInt64)
		case exclusivesubscription.FieldStatus, exclusivesubscription.FieldNotes:
			values[i] = new(sql.NullString)
		case exclusivesubscription.FieldCreatedAt, exclusivesubscription.FieldUpdatedAt, exclusivesubscription.FieldDeletedAt, exclusivesubscription.FieldStartsAt, exclusivesubscription.FieldExpiresAt, exclusivesubscription.FieldAssignedAt, exclusivesubscription.FieldLastRenewalAt, exclusivesubscription.FieldDailyWindowStart, exclusivesubscription.FieldWeeklyWindowStart, exclusivesubscription.FieldMonthlyWindowStart:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExclusiveSubscription fields.
func (_m *ExclusiveSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exclusivesubscription.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case exclusivesubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case exclusivesubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case exclusivesubscription.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case exclusivesubscription.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case exclusivesubscription.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case exclusivesubscription.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case exclusivesubscription.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case exclusivesubscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case exclusivesubscription.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case exclusivesubscription.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case exclusivesubscription.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = value.Time
			}
		case exclusivesubscription.FieldLastRenewalAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_renewal_at", values[i])
			} else if value.Valid {
				_m.LastRenewalAt = new(time.Time)
				*_m.LastRenewalAt = value.Time
			}
		case exclusivesubscription.FieldUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_usd", values[i])
			} else if value.Valid {
				_m.UsageUsd = value.Float64
			}
		case exclusivesubscription.FieldDailyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field daily_window_start", values[i])
			} else if value.Valid {
				_m.DailyWindowStart = new(time.Time)
				*_m.DailyWindowStart = value.Time
			}
		case exclusivesubscription.FieldWeeklyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_window_start", values[i])
			} else if value.Valid {
				_m.WeeklyWindowStart = new(time.Time)
				*_m.WeeklyWindowStart = value.Time
			}
		case exclusivesubscription.FieldMonthlyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_window_start", values[i])
			} else if value.Valid {
				_m.MonthlyWindowStart = new(time.Time)
				*_m.MonthlyWindowStart = value.Time
			}
		case exclusivesubscription.FieldDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_usage_usd", values[i])
			} else if value.Valid {
				_m.DailyUsageUsd = value.Float64
			}
		case exclusivesubscription.FieldWeeklyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_usage_usd", values[i])
			} else if value.Valid {
				_m.WeeklyUsageUsd = value.Float64
			}
		case exclusivesubscription.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
			}
		case exclusivesubscription.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case exclusivesubscription.FieldAssignedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_by", values[i])
			} else if value.Valid {
				_m.AssignedBy = new(int64)
				*_m.AssignedBy = value.Int64
			}
		case exclusivesubscription.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = new(int64)
				*_m.SourceOrderID = value.Int64
			}
		case exclusivesubscription.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case exclusivesubscription.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = new(float64)
				*_m.WeeklyLimitUsd = value.Float64
			}
		case exclusivesubscription.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		case exclusivesubscription.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = new(float64)
				*_m.RateMultiplier = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExclusiveSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *ExclusiveSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExclusiveSubscription.
// Note that you need to call ExclusiveSubscription.Unwrap() before calling this method if this ExclusiveSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExclusiveSubscription) Update() *ExclusiveSubscriptionUpdateOne {
	return NewExclusiveSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExclusiveSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExclusiveSubscription) Unwrap() *ExclusiveSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExclusiveSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExclusiveSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("ExclusiveSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(_m.AssignedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastRenewalAt; v != nil {
		builder.WriteString("last_renewal_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageUsd))
	builder.WriteString(", ")
	if v := _m.DailyWindowStart; v != nil {
		builder.WriteString("daily_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyWindowStart; v != nil {
		builder.WriteString("weekly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyWindowStart; v != nil {
		builder.WriteString("monthly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("weekly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AssignedBy; v != nil {
		builder.WriteString("assigned_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceOrderID; v != nil {
		builder.WriteString("source_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyLimitUsd; v != nil {
		builder.WriteString("weekly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RateMultiplier; v != nil {
		builder.WriteString("rate_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ExclusiveSubscriptions is a parsable slice of ExclusiveSubscription.
type ExclusiveSubscriptions []*ExclusiveSubscription
