// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceRequest is the model entity for the InvoiceRequest schema.
type InvoiceRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail string `json:"user_email,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"user_name,omitempty"`
	// RecipientEmail holds the value of the "recipient_email" field.
	RecipientEmail string `json:"recipient_email,omitempty"`
	// TitleType holds the value of the "title_type" field.
	TitleType string `json:"title_type,omitempty"`
	// TitleName holds the value of the "title_name" field.
	TitleName string `json:"title_name,omitempty"`
	// TaxID holds the value of the "tax_id" field.
	TaxID *string `json:"tax_id,omitempty"`
	// UserRemark holds the value of the "user_remark" field.
	UserRemark *string `json:"user_remark,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// InvoiceNumber holds the value of the "invoice_number" field.
	InvoiceNumber *string `json:"invoice_number,omitempty"`
	// InvoiceDate holds the value of the "invoice_date" field.
	InvoiceDate *time.Time `json:"invoice_date,omitempty"`
	// InvoiceAmount holds the value of the "invoice_amount" field.
	InvoiceAmount *float64 `json:"invoice_amount,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt *time.Time `json:"issued_at,omitempty"`
	// IssuedBy holds the value of the "issued_by" field.
	IssuedBy *int64 `json:"issued_by,omitempty"`
	// RejectReason holds the value of the "reject_reason" field.
	RejectReason *string `json:"reject_reason,omitempty"`
	// EmailSent holds the value of the "email_sent" field.
	EmailSent bool `json:"email_sent,omitempty"`
	// EmailError holds the value of the "email_error" field.
	EmailError *string `json:"email_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvoiceRequestQuery when eager-loading is set.
	Edges        InvoiceRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InvoiceRequestEdges holds the relations/edges for other nodes in the graph.
type InvoiceRequestEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvoiceRequestEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicerequest.FieldEmailSent:
			values[i] = new(sql.NullBool)
		case invoicerequest.FieldAmount, invoicerequest.FieldInvoiceAmount:
			values[i] = new(sql.NullFloat64)
		case invoicerequest.FieldID, invoicerequest.FieldUserID, invoicerequest.FieldIssuedBy:
			values[i] = new(sql.NullInt64)
		case invoicerequest.FieldUserEmail, invoicerequest.FieldUserName, invoicerequest.FieldRecipientEmail, invoicerequest.FieldTitleType, invoicerequest.FieldTitleName, invoicerequest.FieldTaxID, invoicerequest.FieldUserRemark, invoicerequest.FieldStatus, invoicerequest.FieldInvoiceNumber, invoicerequest.FieldRejectReason, invoicerequest.FieldEmailError:
			values[i] = new(sql.NullString)
		case invoicerequest.FieldCreatedAt, invoicerequest.FieldUpdatedAt, invoicerequest.FieldInvoiceDate, invoicerequest.FieldIssuedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceRequest fields.
func (_m *InvoiceRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicerequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoicerequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoicerequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case invoicerequest.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoicerequest.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case invoicerequest.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = value.String
			}
		case invoicerequest.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = value.String
			}
		case invoicerequest.FieldTitleType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_type", values[i])
			} else if value.Valid {
				_m.TitleType = value.String
			}
		case invoicerequest.FieldTitleName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_name", values[i])
			} else if value.Valid {
				_m.TitleName = value.String
			}
		case invoicerequest.FieldTaxID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_id", values[i])
			} else if value.Valid {
				_m.TaxID = new(string)
				*_m.TaxID = value.String
			}
		case invoicerequest.FieldUserRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_remark", values[i])
			} else if value.Valid {
				_m.UserRemark = new(string)
				*_m.UserRemark = value.String
			}
		case invoicerequest.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case invoicerequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoicerequest.FieldInvoiceNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_number", values[i])
			} else if value.Valid {
				_m.InvoiceNumber = new(string)
				*_m.InvoiceNumber = value.String
			}
		case invoicerequest.FieldInvoiceDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_date", values[i])
			} else if value.Valid {
				_m.InvoiceDate = new(time.Time)
				*_m.InvoiceDate = value.Time
			}
		case invoicerequest.FieldInvoiceAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_amount", values[i])
			} else if value.Valid {
				_m.InvoiceAmount = new(float64)
				*_m.InvoiceAmount = value.Float64
			}
		case invoicerequest.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = new(time.Time)
				*_m.IssuedAt = value.Time
			}
		case invoicerequest.FieldIssuedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issued_by", values[i])
			} else if value.Valid {
				_m.IssuedBy = new(int64)
				*_m.IssuedBy = value.Int64
			}
		case invoicerequest.FieldRejectReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reject_reason", values[i])
			} else if value.Valid {
				_m.RejectReason = new(string)
				*_m.RejectReason = value.String
			}
		case invoicerequest.FieldEmailSent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_sent", values[i])
			} else if value.Valid {
				_m.EmailSent = value.Bool
			}
		case invoicerequest.FieldEmailError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_error", values[i])
			} else if value.Valid {
				_m.EmailError = new(string)
				*_m.EmailError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceRequest.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the InvoiceRequest entity.
func (_m *InvoiceRequest) QueryUser() *UserQuery {
	return NewInvoiceRequestClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this InvoiceRequest.
// Note that you need to call InvoiceRequest.Unwrap() before calling this method if this InvoiceRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceRequest) Update() *InvoiceRequestUpdateOne {
	return NewInvoiceRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceRequest) Unwrap() *InvoiceRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceRequest) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("user_name=")
	builder.WriteString(_m.UserName)
	builder.WriteString(", ")
	builder.WriteString("recipient_email=")
	builder.WriteString(_m.RecipientEmail)
	builder.WriteString(", ")
	builder.WriteString("title_type=")
	builder.WriteString(_m.TitleType)
	builder.WriteString(", ")
	builder.WriteString("title_name=")
	builder.WriteString(_m.TitleName)
	builder.WriteString(", ")
	if v := _m.TaxID; v != nil {
		builder.WriteString("tax_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserRemark; v != nil {
		builder.WriteString("user_remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.InvoiceNumber; v != nil {
		builder.WriteString("invoice_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InvoiceDate; v != nil {
		builder.WriteString("invoice_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.InvoiceAmount; v != nil {
		builder.WriteString("invoice_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IssuedAt; v != nil {
		builder.WriteString("issued_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.IssuedBy; v != nil {
		builder.WriteString("issued_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RejectReason; v != nil {
		builder.WriteString("reject_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("email_sent=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmailSent))
	builder.WriteString(", ")
	if v := _m.EmailError; v != nil {
		builder.WriteString("email_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceRequests is a parsable slice of InvoiceRequest.
type InvoiceRequests []*InvoiceRequest
