// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceRequestCreate is the builder for creating a InvoiceRequest entity.
type InvoiceRequestCreate struct {
	config
	mutation *InvoiceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceRequestCreate) SetCreatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableCreatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceRequestCreate) SetUpdatedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceRequestCreate) SetUserID(v int64) *InvoiceRequestCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *InvoiceRequestCreate) SetUserEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *InvoiceRequestCreate) SetUserName(v string) *InvoiceRequestCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUserName(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUserName(*v)
	}
	return _c
}

// SetRecipientEmail sets the "recipient_email" field.
func (_c *InvoiceRequestCreate) SetRecipientEmail(v string) *InvoiceRequestCreate {
	_c.mutation.SetRecipientEmail(v)
	return _c
}

// SetTitleType sets the "title_type" field.
func (_c *InvoiceRequestCreate) SetTitleType(v string) *InvoiceRequestCreate {
	_c.mutation.SetTitleType(v)
	return _c
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableTitleType(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetTitleType(*v)
	}
	return _c
}

// SetTitleName sets the "title_name" field.
func (_c *InvoiceRequestCreate) SetTitleName(v string) *InvoiceRequestCreate {
	_c.mutation.SetTitleName(v)
	return _c
}

// SetTaxID sets the "tax_id" field.
func (_c *InvoiceRequestCreate) SetTaxID(v string) *InvoiceRequestCreate {
	_c.mutation.SetTaxID(v)
	return _c
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableTaxID(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetTaxID(*v)
	}
	return _c
}

// SetUserRemark sets the "user_remark" field.
func (_c *InvoiceRequestCreate) SetUserRemark(v string) *InvoiceRequestCreate {
	_c.mutation.SetUserRemark(v)
	return _c
}

// SetNillableUserRemark sets the "user_remark" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableUserRemark(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetUserRemark(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceRequestCreate) SetAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceRequestCreate) SetStatus(v string) *InvoiceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableStatus(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_c *InvoiceRequestCreate) SetInvoiceNumber(v string) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceNumber(v)
	return _c
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceNumber(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceNumber(*v)
	}
	return _c
}

// SetInvoiceDate sets the "invoice_date" field.
func (_c *InvoiceRequestCreate) SetInvoiceDate(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceDate(v)
	return _c
}

// SetNillableInvoiceDate sets the "invoice_date" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceDate(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceDate(*v)
	}
	return _c
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_c *InvoiceRequestCreate) SetInvoiceAmount(v float64) *InvoiceRequestCreate {
	_c.mutation.SetInvoiceAmount(v)
	return _c
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableInvoiceAmount(v *float64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetInvoiceAmount(*v)
	}
	return _c
}

// SetIssuedAt sets the "issued_at" field.
func (_c *InvoiceRequestCreate) SetIssuedAt(v time.Time) *InvoiceRequestCreate {
	_c.mutation.SetIssuedAt(v)
	return _c
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedAt(*v)
	}
	return _c
}

// SetIssuedBy sets the "issued_by" field.
func (_c *InvoiceRequestCreate) SetIssuedBy(v int64) *InvoiceRequestCreate {
	_c.mutation.SetIssuedBy(v)
	return _c
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableIssuedBy(v *int64) *InvoiceRequestCreate {
	if v != nil {
		_c.SetIssuedBy(*v)
	}
	return _c
}

// SetRejectReason sets the "reject_reason" field.
func (_c *InvoiceRequestCreate) SetRejectReason(v string) *InvoiceRequestCreate {
	_c.mutation.SetRejectReason(v)
	return _c
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableRejectReason(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetRejectReason(*v)
	}
	return _c
}

// SetEmailSent sets the "email_sent" field.
func (_c *InvoiceRequestCreate) SetEmailSent(v bool) *InvoiceRequestCreate {
	_c.mutation.SetEmailSent(v)
	return _c
}

// SetNillableEmailSent sets the "email_sent" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableEmailSent(v *bool) *InvoiceRequestCreate {
	if v != nil {
		_c.SetEmailSent(*v)
	}
	return _c
}

// SetEmailError sets the "email_error" field.
func (_c *InvoiceRequestCreate) SetEmailError(v string) *InvoiceRequestCreate {
	_c.mutation.SetEmailError(v)
	return _c
}

// SetNillableEmailError sets the "email_error" field if the given value is not nil.
func (_c *InvoiceRequestCreate) SetNillableEmailError(v *string) *InvoiceRequestCreate {
	if v != nil {
		_c.SetEmailError(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *InvoiceRequestCreate) SetUser(v *User) *InvoiceRequestCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_c *InvoiceRequestCreate) Mutation() *InvoiceRequestMutation {
	return _c.mutation
}

// Save creates the InvoiceRequest in the database.
func (_c *InvoiceRequestCreate) Save(ctx context.Context) (*InvoiceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceRequestCreate) SaveX(ctx context.Context) *InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceRequestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoicerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoicerequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UserName(); !ok {
		v := invoicerequest.DefaultUserName
		_c.mutation.SetUserName(v)
	}
	if _, ok := _c.mutation.TitleType(); !ok {
		v := invoicerequest.DefaultTitleType
		_c.mutation.SetTitleType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoicerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.EmailSent(); !ok {
		v := invoicerequest.DefaultEmailSent
		_c.mutation.SetEmailSent(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceRequestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceRequest.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceRequest.user_id"`)}
	}
	if _, ok := _c.mutation.UserEmail(); !ok {
		return &ValidationError{Name: "user_email", err: errors.New(`ent: missing required field "InvoiceRequest.user_email"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := invoicerequest.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.user_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserName(); !ok {
		return &ValidationError{Name: "user_name", err: errors.New(`ent: missing required field "InvoiceRequest.user_name"`)}
	}
	if v, ok := _c.mutation.UserName(); ok {
		if err := invoicerequest.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.user_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecipientEmail(); !ok {
		return &ValidationError{Name: "recipient_email", err: errors.New(`ent: missing required field "InvoiceRequest.recipient_email"`)}
	}
	if v, ok := _c.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TitleType(); !ok {
		return &ValidationError{Name: "title_type", err: errors.New(`ent: missing required field "InvoiceRequest.title_type"`)}
	}
	if v, ok := _c.mutation.TitleType(); ok {
		if err := invoicerequest.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TitleName(); !ok {
		return &ValidationError{Name: "title_name", err: errors.New(`ent: missing required field "InvoiceRequest.title_name"`)}
	}
	if v, ok := _c.mutation.TitleName(); ok {
		if err := invoicerequest.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "InvoiceRequest.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.InvoiceNumber(); ok {
		if err := invoicerequest.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmailSent(); !ok {
		return &ValidationError{Name: "email_sent", err: errors.New(`ent: missing required field "InvoiceRequest.email_sent"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "InvoiceRequest.user"`)}
	}
	return nil
}

func (_c *InvoiceRequestCreate) sqlSave(ctx context.Context) (*InvoiceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceRequestCreate) createSpec() (*InvoiceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoicerequest.Table, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoicerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(invoicerequest.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = value
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(invoicerequest.FieldUserName, field.TypeString, value)
		_node.UserName = value
	}
	if value, ok := _c.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
		_node.RecipientEmail = value
	}
	if value, ok := _c.mutation.TitleType(); ok {
		_spec.SetField(invoicerequest.FieldTitleType, field.TypeString, value)
		_node.TitleType = value
	}
	if value, ok := _c.mutation.TitleName(); ok {
		_spec.SetField(invoicerequest.FieldTitleName, field.TypeString, value)
		_node.TitleName = value
	}
	if value, ok := _c.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
		_node.TaxID = &value
	}
	if value, ok := _c.mutation.UserRemark(); ok {
		_spec.SetField(invoicerequest.FieldUserRemark, field.TypeString, value)
		_node.UserRemark = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNumber, field.TypeString, value)
		_node.InvoiceNumber = &value
	}
	if value, ok := _c.mutation.InvoiceDate(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceDate, field.TypeTime, value)
		_node.InvoiceDate = &value
	}
	if value, ok := _c.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64, value)
		_node.InvoiceAmount = &value
	}
	if value, ok := _c.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = &value
	}
	if value, ok := _c.mutation.IssuedBy(); ok {
		_spec.SetField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
		_node.IssuedBy = &value
	}
	if value, ok := _c.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
		_node.RejectReason = &value
	}
	if value, ok := _c.mutation.EmailSent(); ok {
		_spec.SetField(invoicerequest.FieldEmailSent, field.TypeBool, value)
		_node.EmailSent = value
	}
	if value, ok := _c.mutation.EmailError(); ok {
		_spec.SetField(invoicerequest.FieldEmailError, field.TypeString, value)
		_node.EmailError = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertOne {
	_c.conflict = opts
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreate) OnConflictColumns(columns ...string) *InvoiceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceRequestUpsertOne is the builder for "upsert"-ing
	//  one InvoiceRequest node.
	InvoiceRequestUpsertOne struct {
		create *InvoiceRequestCreate
	}

	// InvoiceRequestUpsert is the "OnConflict" setter.
	InvoiceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsert) SetUpdatedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUpdatedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsert) SetUserID(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceRequestUpsert) SetUserEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserEmail)
	return u
}

// SetUserName sets the "user_name" field.
func (u *InvoiceRequestUpsert) SetUserName(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserName, v)
	return u
}

// UpdateUserName sets the "user_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserName() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserName)
	return u
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsert) SetRecipientEmail(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRecipientEmail, v)
	return u
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRecipientEmail() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRecipientEmail)
	return u
}

// SetTitleType sets the "title_type" field.
func (u *InvoiceRequestUpsert) SetTitleType(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTitleType, v)
	return u
}

// UpdateTitleType sets the "title_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTitleType() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTitleType)
	return u
}

// SetTitleName sets the "title_name" field.
func (u *InvoiceRequestUpsert) SetTitleName(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTitleName, v)
	return u
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTitleName() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTitleName)
	return u
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsert) SetTaxID(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldTaxID, v)
	return u
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateTaxID() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldTaxID)
	return u
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceRequestUpsert) ClearTaxID() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldTaxID)
	return u
}

// SetUserRemark sets the "user_remark" field.
func (u *InvoiceRequestUpsert) SetUserRemark(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldUserRemark, v)
	return u
}

// UpdateUserRemark sets the "user_remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateUserRemark() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldUserRemark)
	return u
}

// ClearUserRemark clears the value of the "user_remark" field.
func (u *InvoiceRequestUpsert) ClearUserRemark() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldUserRemark)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsert) SetAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsert) AddAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsert) SetStatus(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateStatus() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldStatus)
	return u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceRequestUpsert) SetInvoiceNumber(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceNumber, v)
	return u
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceNumber() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceNumber)
	return u
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *InvoiceRequestUpsert) ClearInvoiceNumber() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldInvoiceNumber)
	return u
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceRequestUpsert) SetInvoiceDate(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceDate, v)
	return u
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceDate() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceDate)
	return u
}

// ClearInvoiceDate clears the value of the "invoice_date" field.
func (u *InvoiceRequestUpsert) ClearInvoiceDate() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldInvoiceDate)
	return u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceRequestUpsert) SetInvoiceAmount(v float64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldInvoiceAmount, v)
	return u
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateInvoiceAmount() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldInvoiceAmount)
	return u
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceRequestUpsert) AddInvoiceAmount(v float64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldInvoiceAmount, v)
	return u
}

// ClearInvoiceAmount clears the value of the "invoice_amount" field.
func (u *InvoiceRequestUpsert) ClearInvoiceAmount() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldInvoiceAmount)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsert) SetIssuedAt(v time.Time) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedAt() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedAt)
	return u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsert) ClearIssuedAt() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedAt)
	return u
}

// SetIssuedBy sets the "issued_by" field.
func (u *InvoiceRequestUpsert) SetIssuedBy(v int64) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldIssuedBy, v)
	return u
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateIssuedBy() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldIssuedBy)
	return u
}

// AddIssuedBy adds v to the "issued_by" field.
func (u *InvoiceRequestUpsert) AddIssuedBy(v int64) *InvoiceRequestUpsert {
	u.Add(invoicerequest.FieldIssuedBy, v)
	return u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *InvoiceRequestUpsert) ClearIssuedBy() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldIssuedBy)
	return u
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsert) SetRejectReason(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldRejectReason, v)
	return u
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateRejectReason() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldRejectReason)
	return u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsert) ClearRejectReason() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldRejectReason)
	return u
}

// SetEmailSent sets the "email_sent" field.
func (u *InvoiceRequestUpsert) SetEmailSent(v bool) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldEmailSent, v)
	return u
}

// UpdateEmailSent sets the "email_sent" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateEmailSent() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldEmailSent)
	return u
}

// SetEmailError sets the "email_error" field.
func (u *InvoiceRequestUpsert) SetEmailError(v string) *InvoiceRequestUpsert {
	u.Set(invoicerequest.FieldEmailError, v)
	return u
}

// UpdateEmailError sets the "email_error" field to the value that was provided on create.
func (u *InvoiceRequestUpsert) UpdateEmailError() *InvoiceRequestUpsert {
	u.SetExcluded(invoicerequest.FieldEmailError)
	return u
}

// ClearEmailError clears the value of the "email_error" field.
func (u *InvoiceRequestUpsert) ClearEmailError() *InvoiceRequestUpsert {
	u.SetNull(invoicerequest.FieldEmailError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertOne) UpdateNewValues() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoicerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceRequestUpsertOne) Ignore() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertOne) DoNothing() *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreate.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertOne) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUpdatedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertOne) SetUserID(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceRequestUpsertOne) SetUserEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserEmail()
	})
}

// SetUserName sets the "user_name" field.
func (u *InvoiceRequestUpsertOne) SetUserName(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserName(v)
	})
}

// UpdateUserName sets the "user_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserName() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserName()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsertOne) SetRecipientEmail(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRecipientEmail() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetTitleType sets the "title_type" field.
func (u *InvoiceRequestUpsertOne) SetTitleType(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleType(v)
	})
}

// UpdateTitleType sets the "title_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTitleType() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleType()
	})
}

// SetTitleName sets the "title_name" field.
func (u *InvoiceRequestUpsertOne) SetTitleName(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleName(v)
	})
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTitleName() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleName()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsertOne) SetTaxID(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateTaxID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceRequestUpsertOne) ClearTaxID() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearTaxID()
	})
}

// SetUserRemark sets the "user_remark" field.
func (u *InvoiceRequestUpsertOne) SetUserRemark(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserRemark(v)
	})
}

// UpdateUserRemark sets the "user_remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateUserRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserRemark()
	})
}

// ClearUserRemark clears the value of the "user_remark" field.
func (u *InvoiceRequestUpsertOne) ClearUserRemark() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearUserRemark()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsertOne) SetAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsertOne) AddAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertOne) SetStatus(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateStatus() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceNumber(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceNumber() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *InvoiceRequestUpsertOne) ClearInvoiceNumber() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceNumber()
	})
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceDate(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceDate(v)
	})
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceDate() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceDate()
	})
}

// ClearInvoiceDate clears the value of the "invoice_date" field.
func (u *InvoiceRequestUpsertOne) ClearInvoiceDate() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceDate()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceRequestUpsertOne) SetInvoiceAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceRequestUpsertOne) AddInvoiceAmount(v float64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateInvoiceAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// ClearInvoiceAmount clears the value of the "invoice_amount" field.
func (u *InvoiceRequestUpsertOne) ClearInvoiceAmount() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceAmount()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertOne) SetIssuedAt(v time.Time) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedAt() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *InvoiceRequestUpsertOne) SetIssuedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedBy(v)
	})
}

// AddIssuedBy adds v to the "issued_by" field.
func (u *InvoiceRequestUpsertOne) AddIssuedBy(v int64) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateIssuedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *InvoiceRequestUpsertOne) ClearIssuedBy() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedBy()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsertOne) SetRejectReason(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateRejectReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsertOne) ClearRejectReason() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectReason()
	})
}

// SetEmailSent sets the "email_sent" field.
func (u *InvoiceRequestUpsertOne) SetEmailSent(v bool) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmailSent(v)
	})
}

// UpdateEmailSent sets the "email_sent" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateEmailSent() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmailSent()
	})
}

// SetEmailError sets the "email_error" field.
func (u *InvoiceRequestUpsertOne) SetEmailError(v string) *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmailError(v)
	})
}

// UpdateEmailError sets the "email_error" field to the value that was provided on create.
func (u *InvoiceRequestUpsertOne) UpdateEmailError() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmailError()
	})
}

// ClearEmailError clears the value of the "email_error" field.
func (u *InvoiceRequestUpsertOne) ClearEmailError() *InvoiceRequestUpsertOne {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearEmailError()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceRequestCreateBulk is the builder for creating many InvoiceRequest entities in bulk.
type InvoiceRequestCreateBulk struct {
	config
	err      error
	builders []*InvoiceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceRequest entities in the database.
func (_c *InvoiceRequestCreateBulk) Save(ctx context.Context) ([]*InvoiceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) SaveX(ctx context.Context) []*InvoiceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceRequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceRequestUpsertBulk {
	_c.conflict = opts
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceRequestCreateBulk) OnConflictColumns(columns ...string) *InvoiceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceRequestUpsertBulk{
		create: _c,
	}
}

// InvoiceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceRequest nodes.
type InvoiceRequestUpsertBulk struct {
	create *InvoiceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) UpdateNewValues() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoicerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceRequestUpsertBulk) Ignore() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceRequestUpsertBulk) DoNothing() *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceRequestUpsertBulk) Update(set func(*InvoiceRequestUpsert)) *InvoiceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceRequestUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUpdatedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *InvoiceRequestUpsertBulk) SetUserID(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *InvoiceRequestUpsertBulk) SetUserEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserEmail()
	})
}

// SetUserName sets the "user_name" field.
func (u *InvoiceRequestUpsertBulk) SetUserName(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserName(v)
	})
}

// UpdateUserName sets the "user_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserName() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserName()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceRequestUpsertBulk) SetRecipientEmail(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRecipientEmail() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetTitleType sets the "title_type" field.
func (u *InvoiceRequestUpsertBulk) SetTitleType(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleType(v)
	})
}

// UpdateTitleType sets the "title_type" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTitleType() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleType()
	})
}

// SetTitleName sets the "title_name" field.
func (u *InvoiceRequestUpsertBulk) SetTitleName(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTitleName(v)
	})
}

// UpdateTitleName sets the "title_name" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTitleName() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTitleName()
	})
}

// SetTaxID sets the "tax_id" field.
func (u *InvoiceRequestUpsertBulk) SetTaxID(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetTaxID(v)
	})
}

// UpdateTaxID sets the "tax_id" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateTaxID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateTaxID()
	})
}

// ClearTaxID clears the value of the "tax_id" field.
func (u *InvoiceRequestUpsertBulk) ClearTaxID() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearTaxID()
	})
}

// SetUserRemark sets the "user_remark" field.
func (u *InvoiceRequestUpsertBulk) SetUserRemark(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetUserRemark(v)
	})
}

// UpdateUserRemark sets the "user_remark" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateUserRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateUserRemark()
	})
}

// ClearUserRemark clears the value of the "user_remark" field.
func (u *InvoiceRequestUpsertBulk) ClearUserRemark() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearUserRemark()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceRequestUpsertBulk) SetAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceRequestUpsertBulk) AddAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceRequestUpsertBulk) SetStatus(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateStatus() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetInvoiceNumber sets the "invoice_number" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceNumber(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceNumber(v)
	})
}

// UpdateInvoiceNumber sets the "invoice_number" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceNumber() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceNumber()
	})
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (u *InvoiceRequestUpsertBulk) ClearInvoiceNumber() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceNumber()
	})
}

// SetInvoiceDate sets the "invoice_date" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceDate(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceDate(v)
	})
}

// UpdateInvoiceDate sets the "invoice_date" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceDate() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceDate()
	})
}

// ClearInvoiceDate clears the value of the "invoice_date" field.
func (u *InvoiceRequestUpsertBulk) ClearInvoiceDate() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceDate()
	})
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (u *InvoiceRequestUpsertBulk) SetInvoiceAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetInvoiceAmount(v)
	})
}

// AddInvoiceAmount adds v to the "invoice_amount" field.
func (u *InvoiceRequestUpsertBulk) AddInvoiceAmount(v float64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddInvoiceAmount(v)
	})
}

// UpdateInvoiceAmount sets the "invoice_amount" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateInvoiceAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateInvoiceAmount()
	})
}

// ClearInvoiceAmount clears the value of the "invoice_amount" field.
func (u *InvoiceRequestUpsertBulk) ClearInvoiceAmount() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearInvoiceAmount()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedAt(v time.Time) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedAt()
	})
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedAt() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedAt()
	})
}

// SetIssuedBy sets the "issued_by" field.
func (u *InvoiceRequestUpsertBulk) SetIssuedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetIssuedBy(v)
	})
}

// AddIssuedBy adds v to the "issued_by" field.
func (u *InvoiceRequestUpsertBulk) AddIssuedBy(v int64) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.AddIssuedBy(v)
	})
}

// UpdateIssuedBy sets the "issued_by" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateIssuedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateIssuedBy()
	})
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (u *InvoiceRequestUpsertBulk) ClearIssuedBy() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearIssuedBy()
	})
}

// SetRejectReason sets the "reject_reason" field.
func (u *InvoiceRequestUpsertBulk) SetRejectReason(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetRejectReason(v)
	})
}

// UpdateRejectReason sets the "reject_reason" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateRejectReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateRejectReason()
	})
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (u *InvoiceRequestUpsertBulk) ClearRejectReason() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearRejectReason()
	})
}

// SetEmailSent sets the "email_sent" field.
func (u *InvoiceRequestUpsertBulk) SetEmailSent(v bool) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmailSent(v)
	})
}

// UpdateEmailSent sets the "email_sent" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateEmailSent() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmailSent()
	})
}

// SetEmailError sets the "email_error" field.
func (u *InvoiceRequestUpsertBulk) SetEmailError(v string) *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.SetEmailError(v)
	})
}

// UpdateEmailError sets the "email_error" field to the value that was provided on create.
func (u *InvoiceRequestUpsertBulk) UpdateEmailError() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.UpdateEmailError()
	})
}

// ClearEmailError clears the value of the "email_error" field.
func (u *InvoiceRequestUpsertBulk) ClearEmailError() *InvoiceRequestUpsertBulk {
	return u.Update(func(s *InvoiceRequestUpsert) {
		s.ClearEmailError()
	})
}

// Exec executes the query.
func (u *InvoiceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
