// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoicerequest"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// InvoiceRequestUpdate is the builder for updating InvoiceRequest entities.
type InvoiceRequestUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdate) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceRequestUpdate) SetUpdatedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceRequestUpdate) SetUserID(v int64) *InvoiceRequestUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableUserID(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *InvoiceRequestUpdate) SetUserEmail(v string) *InvoiceRequestUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableUserEmail(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *InvoiceRequestUpdate) SetUserName(v string) *InvoiceRequestUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableUserName(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *InvoiceRequestUpdate) SetRecipientEmail(v string) *InvoiceRequestUpdate {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRecipientEmail(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// SetTitleType sets the "title_type" field.
func (_u *InvoiceRequestUpdate) SetTitleType(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTitleType(v)
	return _u
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTitleType(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTitleType(*v)
	}
	return _u
}

// SetTitleName sets the "title_name" field.
func (_u *InvoiceRequestUpdate) SetTitleName(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTitleName(v)
	return _u
}

// SetNillableTitleName sets the "title_name" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTitleName(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTitleName(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *InvoiceRequestUpdate) SetTaxID(v string) *InvoiceRequestUpdate {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableTaxID(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// ClearTaxID clears the value of the "tax_id" field.
func (_u *InvoiceRequestUpdate) ClearTaxID() *InvoiceRequestUpdate {
	_u.mutation.ClearTaxID()
	return _u
}

// SetUserRemark sets the "user_remark" field.
func (_u *InvoiceRequestUpdate) SetUserRemark(v string) *InvoiceRequestUpdate {
	_u.mutation.SetUserRemark(v)
	return _u
}

// SetNillableUserRemark sets the "user_remark" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableUserRemark(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetUserRemark(*v)
	}
	return _u
}

// ClearUserRemark clears the value of the "user_remark" field.
func (_u *InvoiceRequestUpdate) ClearUserRemark() *InvoiceRequestUpdate {
	_u.mutation.ClearUserRemark()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceRequestUpdate) SetAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceRequestUpdate) AddAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdate) SetStatus(v string) *InvoiceRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableStatus(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_u *InvoiceRequestUpdate) SetInvoiceNumber(v string) *InvoiceRequestUpdate {
	_u.mutation.SetInvoiceNumber(v)
	return _u
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableInvoiceNumber(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetInvoiceNumber(*v)
	}
	return _u
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (_u *InvoiceRequestUpdate) ClearInvoiceNumber() *InvoiceRequestUpdate {
	_u.mutation.ClearInvoiceNumber()
	return _u
}

// SetInvoiceDate sets the "invoice_date" field.
func (_u *InvoiceRequestUpdate) SetInvoiceDate(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetInvoiceDate(v)
	return _u
}

// SetNillableInvoiceDate sets the "invoice_date" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableInvoiceDate(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetInvoiceDate(*v)
	}
	return _u
}

// ClearInvoiceDate clears the value of the "invoice_date" field.
func (_u *InvoiceRequestUpdate) ClearInvoiceDate() *InvoiceRequestUpdate {
	_u.mutation.ClearInvoiceDate()
	return _u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_u *InvoiceRequestUpdate) SetInvoiceAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.ResetInvoiceAmount()
	_u.mutation.SetInvoiceAmount(v)
	return _u
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableInvoiceAmount(v *float64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetInvoiceAmount(*v)
	}
	return _u
}

// AddInvoiceAmount adds value to the "invoice_amount" field.
func (_u *InvoiceRequestUpdate) AddInvoiceAmount(v float64) *InvoiceRequestUpdate {
	_u.mutation.AddInvoiceAmount(v)
	return _u
}

// ClearInvoiceAmount clears the value of the "invoice_amount" field.
func (_u *InvoiceRequestUpdate) ClearInvoiceAmount() *InvoiceRequestUpdate {
	_u.mutation.ClearInvoiceAmount()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdate) SetIssuedAt(v time.Time) *InvoiceRequestUpdate {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdate) ClearIssuedAt() *InvoiceRequestUpdate {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *InvoiceRequestUpdate) SetIssuedBy(v int64) *InvoiceRequestUpdate {
	_u.mutation.ResetIssuedBy()
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableIssuedBy(v *int64) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// AddIssuedBy adds value to the "issued_by" field.
func (_u *InvoiceRequestUpdate) AddIssuedBy(v int64) *InvoiceRequestUpdate {
	_u.mutation.AddIssuedBy(v)
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *InvoiceRequestUpdate) ClearIssuedBy() *InvoiceRequestUpdate {
	_u.mutation.ClearIssuedBy()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *InvoiceRequestUpdate) SetRejectReason(v string) *InvoiceRequestUpdate {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableRejectReason(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *InvoiceRequestUpdate) ClearRejectReason() *InvoiceRequestUpdate {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetEmailSent sets the "email_sent" field.
func (_u *InvoiceRequestUpdate) SetEmailSent(v bool) *InvoiceRequestUpdate {
	_u.mutation.SetEmailSent(v)
	return _u
}

// SetNillableEmailSent sets the "email_sent" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableEmailSent(v *bool) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetEmailSent(*v)
	}
	return _u
}

// SetEmailError sets the "email_error" field.
func (_u *InvoiceRequestUpdate) SetEmailError(v string) *InvoiceRequestUpdate {
	_u.mutation.SetEmailError(v)
	return _u
}

// SetNillableEmailError sets the "email_error" field if the given value is not nil.
func (_u *InvoiceRequestUpdate) SetNillableEmailError(v *string) *InvoiceRequestUpdate {
	if v != nil {
		_u.SetEmailError(*v)
	}
	return _u
}

// ClearEmailError clears the value of the "email_error" field.
func (_u *InvoiceRequestUpdate) ClearEmailError() *InvoiceRequestUpdate {
	_u.mutation.ClearEmailError()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceRequestUpdate) SetUser(v *User) *InvoiceRequestUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdate) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceRequestUpdate) ClearUser() *InvoiceRequestUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoicerequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdate) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := invoicerequest.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := invoicerequest.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TitleType(); ok {
		if err := invoicerequest.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TitleName(); ok {
		if err := invoicerequest.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNumber(); ok {
		if err := invoicerequest.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_number": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceRequest.user"`)
	}
	return nil
}

func (_u *InvoiceRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(invoicerequest.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(invoicerequest.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleType(); ok {
		_spec.SetField(invoicerequest.FieldTitleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleName(); ok {
		_spec.SetField(invoicerequest.FieldTitleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
	}
	if _u.mutation.TaxIDCleared() {
		_spec.ClearField(invoicerequest.FieldTaxID, field.TypeString)
	}
	if value, ok := _u.mutation.UserRemark(); ok {
		_spec.SetField(invoicerequest.FieldUserRemark, field.TypeString, value)
	}
	if _u.mutation.UserRemarkCleared() {
		_spec.ClearField(invoicerequest.FieldUserRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNumber, field.TypeString, value)
	}
	if _u.mutation.InvoiceNumberCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceNumber, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceDate(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceDate, field.TypeTime, value)
	}
	if _u.mutation.InvoiceDateCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceDate, field.TypeTime)
	}
	if value, ok := _u.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceAmount(); ok {
		_spec.AddField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if _u.mutation.InvoiceAmountCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedBy(); ok {
		_spec.SetField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedBy(); ok {
		_spec.AddField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if _u.mutation.IssuedByCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(invoicerequest.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.EmailSent(); ok {
		_spec.SetField(invoicerequest.FieldEmailSent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EmailError(); ok {
		_spec.SetField(invoicerequest.FieldEmailError, field.TypeString, value)
	}
	if _u.mutation.EmailErrorCleared() {
		_spec.ClearField(invoicerequest.FieldEmailError, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceRequestUpdateOne is the builder for updating a single InvoiceRequest entity.
type InvoiceRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceRequestUpdateOne) SetUpdatedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceRequestUpdateOne) SetUserID(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableUserID(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *InvoiceRequestUpdateOne) SetUserEmail(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableUserEmail(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *InvoiceRequestUpdateOne) SetUserName(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableUserName(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *InvoiceRequestUpdateOne) SetRecipientEmail(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRecipientEmail(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// SetTitleType sets the "title_type" field.
func (_u *InvoiceRequestUpdateOne) SetTitleType(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTitleType(v)
	return _u
}

// SetNillableTitleType sets the "title_type" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTitleType(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTitleType(*v)
	}
	return _u
}

// SetTitleName sets the "title_name" field.
func (_u *InvoiceRequestUpdateOne) SetTitleName(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTitleName(v)
	return _u
}

// SetNillableTitleName sets the "title_name" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTitleName(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTitleName(*v)
	}
	return _u
}

// SetTaxID sets the "tax_id" field.
func (_u *InvoiceRequestUpdateOne) SetTaxID(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetTaxID(v)
	return _u
}

// SetNillableTaxID sets the "tax_id" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableTaxID(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetTaxID(*v)
	}
	return _u
}

// ClearTaxID clears the value of the "tax_id" field.
func (_u *InvoiceRequestUpdateOne) ClearTaxID() *InvoiceRequestUpdateOne {
	_u.mutation.ClearTaxID()
	return _u
}

// SetUserRemark sets the "user_remark" field.
func (_u *InvoiceRequestUpdateOne) SetUserRemark(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetUserRemark(v)
	return _u
}

// SetNillableUserRemark sets the "user_remark" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableUserRemark(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetUserRemark(*v)
	}
	return _u
}

// ClearUserRemark clears the value of the "user_remark" field.
func (_u *InvoiceRequestUpdateOne) ClearUserRemark() *InvoiceRequestUpdateOne {
	_u.mutation.ClearUserRemark()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceRequestUpdateOne) SetAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceRequestUpdateOne) AddAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceRequestUpdateOne) SetStatus(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableStatus(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInvoiceNumber sets the "invoice_number" field.
func (_u *InvoiceRequestUpdateOne) SetInvoiceNumber(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetInvoiceNumber(v)
	return _u
}

// SetNillableInvoiceNumber sets the "invoice_number" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableInvoiceNumber(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceNumber(*v)
	}
	return _u
}

// ClearInvoiceNumber clears the value of the "invoice_number" field.
func (_u *InvoiceRequestUpdateOne) ClearInvoiceNumber() *InvoiceRequestUpdateOne {
	_u.mutation.ClearInvoiceNumber()
	return _u
}

// SetInvoiceDate sets the "invoice_date" field.
func (_u *InvoiceRequestUpdateOne) SetInvoiceDate(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetInvoiceDate(v)
	return _u
}

// SetNillableInvoiceDate sets the "invoice_date" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableInvoiceDate(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceDate(*v)
	}
	return _u
}

// ClearInvoiceDate clears the value of the "invoice_date" field.
func (_u *InvoiceRequestUpdateOne) ClearInvoiceDate() *InvoiceRequestUpdateOne {
	_u.mutation.ClearInvoiceDate()
	return _u
}

// SetInvoiceAmount sets the "invoice_amount" field.
func (_u *InvoiceRequestUpdateOne) SetInvoiceAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetInvoiceAmount()
	_u.mutation.SetInvoiceAmount(v)
	return _u
}

// SetNillableInvoiceAmount sets the "invoice_amount" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableInvoiceAmount(v *float64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetInvoiceAmount(*v)
	}
	return _u
}

// AddInvoiceAmount adds value to the "invoice_amount" field.
func (_u *InvoiceRequestUpdateOne) AddInvoiceAmount(v float64) *InvoiceRequestUpdateOne {
	_u.mutation.AddInvoiceAmount(v)
	return _u
}

// ClearInvoiceAmount clears the value of the "invoice_amount" field.
func (_u *InvoiceRequestUpdateOne) ClearInvoiceAmount() *InvoiceRequestUpdateOne {
	_u.mutation.ClearInvoiceAmount()
	return _u
}

// SetIssuedAt sets the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) SetIssuedAt(v time.Time) *InvoiceRequestUpdateOne {
	_u.mutation.SetIssuedAt(v)
	return _u
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableIssuedAt(v *time.Time) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetIssuedAt(*v)
	}
	return _u
}

// ClearIssuedAt clears the value of the "issued_at" field.
func (_u *InvoiceRequestUpdateOne) ClearIssuedAt() *InvoiceRequestUpdateOne {
	_u.mutation.ClearIssuedAt()
	return _u
}

// SetIssuedBy sets the "issued_by" field.
func (_u *InvoiceRequestUpdateOne) SetIssuedBy(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.ResetIssuedBy()
	_u.mutation.SetIssuedBy(v)
	return _u
}

// SetNillableIssuedBy sets the "issued_by" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableIssuedBy(v *int64) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetIssuedBy(*v)
	}
	return _u
}

// AddIssuedBy adds value to the "issued_by" field.
func (_u *InvoiceRequestUpdateOne) AddIssuedBy(v int64) *InvoiceRequestUpdateOne {
	_u.mutation.AddIssuedBy(v)
	return _u
}

// ClearIssuedBy clears the value of the "issued_by" field.
func (_u *InvoiceRequestUpdateOne) ClearIssuedBy() *InvoiceRequestUpdateOne {
	_u.mutation.ClearIssuedBy()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *InvoiceRequestUpdateOne) SetRejectReason(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableRejectReason(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *InvoiceRequestUpdateOne) ClearRejectReason() *InvoiceRequestUpdateOne {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetEmailSent sets the "email_sent" field.
func (_u *InvoiceRequestUpdateOne) SetEmailSent(v bool) *InvoiceRequestUpdateOne {
	_u.mutation.SetEmailSent(v)
	return _u
}

// SetNillableEmailSent sets the "email_sent" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableEmailSent(v *bool) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetEmailSent(*v)
	}
	return _u
}

// SetEmailError sets the "email_error" field.
func (_u *InvoiceRequestUpdateOne) SetEmailError(v string) *InvoiceRequestUpdateOne {
	_u.mutation.SetEmailError(v)
	return _u
}

// SetNillableEmailError sets the "email_error" field if the given value is not nil.
func (_u *InvoiceRequestUpdateOne) SetNillableEmailError(v *string) *InvoiceRequestUpdateOne {
	if v != nil {
		_u.SetEmailError(*v)
	}
	return _u
}

// ClearEmailError clears the value of the "email_error" field.
func (_u *InvoiceRequestUpdateOne) ClearEmailError() *InvoiceRequestUpdateOne {
	_u.mutation.ClearEmailError()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *InvoiceRequestUpdateOne) SetUser(v *User) *InvoiceRequestUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the InvoiceRequestMutation object of the builder.
func (_u *InvoiceRequestUpdateOne) Mutation() *InvoiceRequestMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *InvoiceRequestUpdateOne) ClearUser() *InvoiceRequestUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the InvoiceRequestUpdate builder.
func (_u *InvoiceRequestUpdateOne) Where(ps ...predicate.InvoiceRequest) *InvoiceRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceRequestUpdateOne) Select(field string, fields ...string) *InvoiceRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceRequest entity.
func (_u *InvoiceRequestUpdateOne) Save(ctx context.Context) (*InvoiceRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) SaveX(ctx context.Context) *InvoiceRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoicerequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceRequestUpdateOne) check() error {
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := invoicerequest.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := invoicerequest.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := invoicerequest.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TitleType(); ok {
		if err := invoicerequest.TitleTypeValidator(v); err != nil {
			return &ValidationError{Name: "title_type", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TitleName(); ok {
		if err := invoicerequest.TitleNameValidator(v); err != nil {
			return &ValidationError{Name: "title_name", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.title_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxID(); ok {
		if err := invoicerequest.TaxIDValidator(v); err != nil {
			return &ValidationError{Name: "tax_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.tax_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoicerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InvoiceNumber(); ok {
		if err := invoicerequest.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "InvoiceRequest.invoice_number": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InvoiceRequest.user"`)
	}
	return nil
}

func (_u *InvoiceRequestUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoicerequest.Table, invoicerequest.Columns, sqlgraph.NewFieldSpec(invoicerequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicerequest.FieldID)
		for _, f := range fields {
			if !invoicerequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicerequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoicerequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(invoicerequest.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(invoicerequest.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(invoicerequest.FieldRecipientEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleType(); ok {
		_spec.SetField(invoicerequest.FieldTitleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleName(); ok {
		_spec.SetField(invoicerequest.FieldTitleName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxID(); ok {
		_spec.SetField(invoicerequest.FieldTaxID, field.TypeString, value)
	}
	if _u.mutation.TaxIDCleared() {
		_spec.ClearField(invoicerequest.FieldTaxID, field.TypeString)
	}
	if value, ok := _u.mutation.UserRemark(); ok {
		_spec.SetField(invoicerequest.FieldUserRemark, field.TypeString, value)
	}
	if _u.mutation.UserRemarkCleared() {
		_spec.ClearField(invoicerequest.FieldUserRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoicerequest.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoicerequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InvoiceNumber(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceNumber, field.TypeString, value)
	}
	if _u.mutation.InvoiceNumberCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceNumber, field.TypeString)
	}
	if value, ok := _u.mutation.InvoiceDate(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceDate, field.TypeTime, value)
	}
	if _u.mutation.InvoiceDateCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceDate, field.TypeTime)
	}
	if value, ok := _u.mutation.InvoiceAmount(); ok {
		_spec.SetField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInvoiceAmount(); ok {
		_spec.AddField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64, value)
	}
	if _u.mutation.InvoiceAmountCleared() {
		_spec.ClearField(invoicerequest.FieldInvoiceAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IssuedAt(); ok {
		_spec.SetField(invoicerequest.FieldIssuedAt, field.TypeTime, value)
	}
	if _u.mutation.IssuedAtCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedBy(); ok {
		_spec.SetField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedBy(); ok {
		_spec.AddField(invoicerequest.FieldIssuedBy, field.TypeInt64, value)
	}
	if _u.mutation.IssuedByCleared() {
		_spec.ClearField(invoicerequest.FieldIssuedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(invoicerequest.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(invoicerequest.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.EmailSent(); ok {
		_spec.SetField(invoicerequest.FieldEmailSent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EmailError(); ok {
		_spec.SetField(invoicerequest.FieldEmailError, field.TypeString, value)
	}
	if _u.mutation.EmailErrorCleared() {
		_spec.ClearField(invoicerequest.FieldEmailError, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoicerequest.UserTable,
			Columns: []string{invoicerequest.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicerequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
