// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invoicerequest type in the database.
	Label = "invoice_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldRecipientEmail holds the string denoting the recipient_email field in the database.
	FieldRecipientEmail = "recipient_email"
	// FieldTitleType holds the string denoting the title_type field in the database.
	FieldTitleType = "title_type"
	// FieldTitleName holds the string denoting the title_name field in the database.
	FieldTitleName = "title_name"
	// FieldTaxID holds the string denoting the tax_id field in the database.
	FieldTaxID = "tax_id"
	// FieldUserRemark holds the string denoting the user_remark field in the database.
	FieldUserRemark = "user_remark"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldInvoiceNumber holds the string denoting the invoice_number field in the database.
	FieldInvoiceNumber = "invoice_number"
	// FieldInvoiceDate holds the string denoting the invoice_date field in the database.
	FieldInvoiceDate = "invoice_date"
	// FieldInvoiceAmount holds the string denoting the invoice_amount field in the database.
	FieldInvoiceAmount = "invoice_amount"
	// FieldIssuedAt holds the string denoting the issued_at field in the database.
	FieldIssuedAt = "issued_at"
	// FieldIssuedBy holds the string denoting the issued_by field in the database.
	FieldIssuedBy = "issued_by"
	// FieldRejectReason holds the string denoting the reject_reason field in the database.
	FieldRejectReason = "reject_reason"
	// FieldEmailSent holds the string denoting the email_sent field in the database.
	FieldEmailSent = "email_sent"
	// FieldEmailError holds the string denoting the email_error field in the database.
	FieldEmailError = "email_error"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the invoicerequest in the database.
	Table = "invoice_requests"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "invoice_requests"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for invoicerequest fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldUserEmail,
	FieldUserName,
	FieldRecipientEmail,
	FieldTitleType,
	FieldTitleName,
	FieldTaxID,
	FieldUserRemark,
	FieldAmount,
	FieldStatus,
	FieldInvoiceNumber,
	FieldInvoiceDate,
	FieldInvoiceAmount,
	FieldIssuedAt,
	FieldIssuedBy,
	FieldRejectReason,
	FieldEmailSent,
	FieldEmailError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// DefaultUserName holds the default value on creation for the "user_name" field.
	DefaultUserName string
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// RecipientEmailValidator is a validator for the "recipient_email" field. It is called by the builders before save.
	RecipientEmailValidator func(string) error
	// DefaultTitleType holds the default value on creation for the "title_type" field.
	DefaultTitleType string
	// TitleTypeValidator is a validator for the "title_type" field. It is called by the builders before save.
	TitleTypeValidator func(string) error
	// TitleNameValidator is a validator for the "title_name" field. It is called by the builders before save.
	TitleNameValidator func(string) error
	// TaxIDValidator is a validator for the "tax_id" field. It is called by the builders before save.
	TaxIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// InvoiceNumberValidator is a validator for the "invoice_number" field. It is called by the builders before save.
	InvoiceNumberValidator func(string) error
	// DefaultEmailSent holds the default value on creation for the "email_sent" field.
	DefaultEmailSent bool
)

// OrderOption defines the ordering options for the InvoiceRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByRecipientEmail orders the results by the recipient_email field.
func ByRecipientEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientEmail, opts...).ToFunc()
}

// ByTitleType orders the results by the title_type field.
func ByTitleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleType, opts...).ToFunc()
}

// ByTitleName orders the results by the title_name field.
func ByTitleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleName, opts...).ToFunc()
}

// ByTaxID orders the results by the tax_id field.
func ByTaxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxID, opts...).ToFunc()
}

// ByUserRemark orders the results by the user_remark field.
func ByUserRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserRemark, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInvoiceNumber orders the results by the invoice_number field.
func ByInvoiceNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceNumber, opts...).ToFunc()
}

// ByInvoiceDate orders the results by the invoice_date field.
func ByInvoiceDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceDate, opts...).ToFunc()
}

// ByInvoiceAmount orders the results by the invoice_amount field.
func ByInvoiceAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceAmount, opts...).ToFunc()
}

// ByIssuedAt orders the results by the issued_at field.
func ByIssuedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedAt, opts...).ToFunc()
}

// ByIssuedBy orders the results by the issued_by field.
func ByIssuedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuedBy, opts...).ToFunc()
}

// ByRejectReason orders the results by the reject_reason field.
func ByRejectReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectReason, opts...).ToFunc()
}

// ByEmailSent orders the results by the email_sent field.
func ByEmailSent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailSent, opts...).ToFunc()
}

// ByEmailError orders the results by the email_error field.
func ByEmailError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailError, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
