// Code generated by ent, DO NOT EDIT.

package invoicerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// UserEmail applies equality check predicate on the "user_email" field. It's identical to UserEmailEQ.
func UserEmail(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserEmail, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserName, v))
}

// RecipientEmail applies equality check predicate on the "recipient_email" field. It's identical to RecipientEmailEQ.
func RecipientEmail(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRecipientEmail, v))
}

// TitleType applies equality check predicate on the "title_type" field. It's identical to TitleTypeEQ.
func TitleType(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleType, v))
}

// TitleName applies equality check predicate on the "title_name" field. It's identical to TitleNameEQ.
func TitleName(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleName, v))
}

// TaxID applies equality check predicate on the "tax_id" field. It's identical to TaxIDEQ.
func TaxID(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxID, v))
}

// UserRemark applies equality check predicate on the "user_remark" field. It's identical to UserRemarkEQ.
func UserRemark(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserRemark, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// InvoiceNumber applies equality check predicate on the "invoice_number" field. It's identical to InvoiceNumberEQ.
func InvoiceNumber(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceNumber, v))
}

// InvoiceDate applies equality check predicate on the "invoice_date" field. It's identical to InvoiceDateEQ.
func InvoiceDate(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceDate, v))
}

// InvoiceAmount applies equality check predicate on the "invoice_amount" field. It's identical to InvoiceAmountEQ.
func InvoiceAmount(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceAmount, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedBy applies equality check predicate on the "issued_by" field. It's identical to IssuedByEQ.
func IssuedBy(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedBy, v))
}

// RejectReason applies equality check predicate on the "reject_reason" field. It's identical to RejectReasonEQ.
func RejectReason(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRejectReason, v))
}

// EmailSent applies equality check predicate on the "email_sent" field. It's identical to EmailSentEQ.
func EmailSent(v bool) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmailSent, v))
}

// EmailError applies equality check predicate on the "email_error" field. It's identical to EmailErrorEQ.
func EmailError(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmailError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserEmailEQ applies the EQ predicate on the "user_email" field.
func UserEmailEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserEmail, v))
}

// UserEmailNEQ applies the NEQ predicate on the "user_email" field.
func UserEmailNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserEmail, v))
}

// UserEmailIn applies the In predicate on the "user_email" field.
func UserEmailIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserEmail, vs...))
}

// UserEmailNotIn applies the NotIn predicate on the "user_email" field.
func UserEmailNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserEmail, vs...))
}

// UserEmailGT applies the GT predicate on the "user_email" field.
func UserEmailGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUserEmail, v))
}

// UserEmailGTE applies the GTE predicate on the "user_email" field.
func UserEmailGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUserEmail, v))
}

// UserEmailLT applies the LT predicate on the "user_email" field.
func UserEmailLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUserEmail, v))
}

// UserEmailLTE applies the LTE predicate on the "user_email" field.
func UserEmailLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUserEmail, v))
}

// UserEmailContains applies the Contains predicate on the "user_email" field.
func UserEmailContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldUserEmail, v))
}

// UserEmailHasPrefix applies the HasPrefix predicate on the "user_email" field.
func UserEmailHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldUserEmail, v))
}

// UserEmailHasSuffix applies the HasSuffix predicate on the "user_email" field.
func UserEmailHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldUserEmail, v))
}

// UserEmailEqualFold applies the EqualFold predicate on the "user_email" field.
func UserEmailEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldUserEmail, v))
}

// UserEmailContainsFold applies the ContainsFold predicate on the "user_email" field.
func UserEmailContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldUserEmail, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldUserName, v))
}

// RecipientEmailEQ applies the EQ predicate on the "recipient_email" field.
func RecipientEmailEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientEmailNEQ applies the NEQ predicate on the "recipient_email" field.
func RecipientEmailNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRecipientEmail, v))
}

// RecipientEmailIn applies the In predicate on the "recipient_email" field.
func RecipientEmailIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRecipientEmail, vs...))
}

// RecipientEmailNotIn applies the NotIn predicate on the "recipient_email" field.
func RecipientEmailNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRecipientEmail, vs...))
}

// RecipientEmailGT applies the GT predicate on the "recipient_email" field.
func RecipientEmailGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRecipientEmail, v))
}

// RecipientEmailGTE applies the GTE predicate on the "recipient_email" field.
func RecipientEmailGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRecipientEmail, v))
}

// RecipientEmailLT applies the LT predicate on the "recipient_email" field.
func RecipientEmailLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRecipientEmail, v))
}

// RecipientEmailLTE applies the LTE predicate on the "recipient_email" field.
func RecipientEmailLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRecipientEmail, v))
}

// RecipientEmailContains applies the Contains predicate on the "recipient_email" field.
func RecipientEmailContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRecipientEmail, v))
}

// RecipientEmailHasPrefix applies the HasPrefix predicate on the "recipient_email" field.
func RecipientEmailHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRecipientEmail, v))
}

// RecipientEmailHasSuffix applies the HasSuffix predicate on the "recipient_email" field.
func RecipientEmailHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRecipientEmail, v))
}

// RecipientEmailEqualFold applies the EqualFold predicate on the "recipient_email" field.
func RecipientEmailEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRecipientEmail, v))
}

// RecipientEmailContainsFold applies the ContainsFold predicate on the "recipient_email" field.
func RecipientEmailContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRecipientEmail, v))
}

// TitleTypeEQ applies the EQ predicate on the "title_type" field.
func TitleTypeEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleType, v))
}

// TitleTypeNEQ applies the NEQ predicate on the "title_type" field.
func TitleTypeNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTitleType, v))
}

// TitleTypeIn applies the In predicate on the "title_type" field.
func TitleTypeIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTitleType, vs...))
}

// TitleTypeNotIn applies the NotIn predicate on the "title_type" field.
func TitleTypeNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTitleType, vs...))
}

// TitleTypeGT applies the GT predicate on the "title_type" field.
func TitleTypeGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTitleType, v))
}

// TitleTypeGTE applies the GTE predicate on the "title_type" field.
func TitleTypeGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTitleType, v))
}

// TitleTypeLT applies the LT predicate on the "title_type" field.
func TitleTypeLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTitleType, v))
}

// TitleTypeLTE applies the LTE predicate on the "title_type" field.
func TitleTypeLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTitleType, v))
}

// TitleTypeContains applies the Contains predicate on the "title_type" field.
func TitleTypeContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTitleType, v))
}

// TitleTypeHasPrefix applies the HasPrefix predicate on the "title_type" field.
func TitleTypeHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTitleType, v))
}

// TitleTypeHasSuffix applies the HasSuffix predicate on the "title_type" field.
func TitleTypeHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTitleType, v))
}

// TitleTypeEqualFold applies the EqualFold predicate on the "title_type" field.
func TitleTypeEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTitleType, v))
}

// TitleTypeContainsFold applies the ContainsFold predicate on the "title_type" field.
func TitleTypeContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTitleType, v))
}

// TitleNameEQ applies the EQ predicate on the "title_name" field.
func TitleNameEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTitleName, v))
}

// TitleNameNEQ applies the NEQ predicate on the "title_name" field.
func TitleNameNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTitleName, v))
}

// TitleNameIn applies the In predicate on the "title_name" field.
func TitleNameIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTitleName, vs...))
}

// TitleNameNotIn applies the NotIn predicate on the "title_name" field.
func TitleNameNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTitleName, vs...))
}

// TitleNameGT applies the GT predicate on the "title_name" field.
func TitleNameGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTitleName, v))
}

// TitleNameGTE applies the GTE predicate on the "title_name" field.
func TitleNameGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTitleName, v))
}

// TitleNameLT applies the LT predicate on the "title_name" field.
func TitleNameLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTitleName, v))
}

// TitleNameLTE applies the LTE predicate on the "title_name" field.
func TitleNameLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTitleName, v))
}

// TitleNameContains applies the Contains predicate on the "title_name" field.
func TitleNameContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTitleName, v))
}

// TitleNameHasPrefix applies the HasPrefix predicate on the "title_name" field.
func TitleNameHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTitleName, v))
}

// TitleNameHasSuffix applies the HasSuffix predicate on the "title_name" field.
func TitleNameHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTitleName, v))
}

// TitleNameEqualFold applies the EqualFold predicate on the "title_name" field.
func TitleNameEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTitleName, v))
}

// TitleNameContainsFold applies the ContainsFold predicate on the "title_name" field.
func TitleNameContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTitleName, v))
}

// TaxIDEQ applies the EQ predicate on the "tax_id" field.
func TaxIDEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldTaxID, v))
}

// TaxIDNEQ applies the NEQ predicate on the "tax_id" field.
func TaxIDNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldTaxID, v))
}

// TaxIDIn applies the In predicate on the "tax_id" field.
func TaxIDIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldTaxID, vs...))
}

// TaxIDNotIn applies the NotIn predicate on the "tax_id" field.
func TaxIDNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldTaxID, vs...))
}

// TaxIDGT applies the GT predicate on the "tax_id" field.
func TaxIDGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldTaxID, v))
}

// TaxIDGTE applies the GTE predicate on the "tax_id" field.
func TaxIDGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldTaxID, v))
}

// TaxIDLT applies the LT predicate on the "tax_id" field.
func TaxIDLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldTaxID, v))
}

// TaxIDLTE applies the LTE predicate on the "tax_id" field.
func TaxIDLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldTaxID, v))
}

// TaxIDContains applies the Contains predicate on the "tax_id" field.
func TaxIDContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldTaxID, v))
}

// TaxIDHasPrefix applies the HasPrefix predicate on the "tax_id" field.
func TaxIDHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldTaxID, v))
}

// TaxIDHasSuffix applies the HasSuffix predicate on the "tax_id" field.
func TaxIDHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldTaxID, v))
}

// TaxIDIsNil applies the IsNil predicate on the "tax_id" field.
func TaxIDIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldTaxID))
}

// TaxIDNotNil applies the NotNil predicate on the "tax_id" field.
func TaxIDNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldTaxID))
}

// TaxIDEqualFold applies the EqualFold predicate on the "tax_id" field.
func TaxIDEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldTaxID, v))
}

// TaxIDContainsFold applies the ContainsFold predicate on the "tax_id" field.
func TaxIDContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldTaxID, v))
}

// UserRemarkEQ applies the EQ predicate on the "user_remark" field.
func UserRemarkEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldUserRemark, v))
}

// UserRemarkNEQ applies the NEQ predicate on the "user_remark" field.
func UserRemarkNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldUserRemark, v))
}

// UserRemarkIn applies the In predicate on the "user_remark" field.
func UserRemarkIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldUserRemark, vs...))
}

// UserRemarkNotIn applies the NotIn predicate on the "user_remark" field.
func UserRemarkNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldUserRemark, vs...))
}

// UserRemarkGT applies the GT predicate on the "user_remark" field.
func UserRemarkGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldUserRemark, v))
}

// UserRemarkGTE applies the GTE predicate on the "user_remark" field.
func UserRemarkGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldUserRemark, v))
}

// UserRemarkLT applies the LT predicate on the "user_remark" field.
func UserRemarkLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldUserRemark, v))
}

// UserRemarkLTE applies the LTE predicate on the "user_remark" field.
func UserRemarkLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldUserRemark, v))
}

// UserRemarkContains applies the Contains predicate on the "user_remark" field.
func UserRemarkContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldUserRemark, v))
}

// UserRemarkHasPrefix applies the HasPrefix predicate on the "user_remark" field.
func UserRemarkHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldUserRemark, v))
}

// UserRemarkHasSuffix applies the HasSuffix predicate on the "user_remark" field.
func UserRemarkHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldUserRemark, v))
}

// UserRemarkIsNil applies the IsNil predicate on the "user_remark" field.
func UserRemarkIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldUserRemark))
}

// UserRemarkNotNil applies the NotNil predicate on the "user_remark" field.
func UserRemarkNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldUserRemark))
}

// UserRemarkEqualFold applies the EqualFold predicate on the "user_remark" field.
func UserRemarkEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldUserRemark, v))
}

// UserRemarkContainsFold applies the ContainsFold predicate on the "user_remark" field.
func UserRemarkContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldUserRemark, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldStatus, v))
}

// InvoiceNumberEQ applies the EQ predicate on the "invoice_number" field.
func InvoiceNumberEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberNEQ applies the NEQ predicate on the "invoice_number" field.
func InvoiceNumberNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceNumber, v))
}

// InvoiceNumberIn applies the In predicate on the "invoice_number" field.
func InvoiceNumberIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberNotIn applies the NotIn predicate on the "invoice_number" field.
func InvoiceNumberNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceNumber, vs...))
}

// InvoiceNumberGT applies the GT predicate on the "invoice_number" field.
func InvoiceNumberGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceNumber, v))
}

// InvoiceNumberGTE applies the GTE predicate on the "invoice_number" field.
func InvoiceNumberGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceNumber, v))
}

// InvoiceNumberLT applies the LT predicate on the "invoice_number" field.
func InvoiceNumberLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceNumber, v))
}

// InvoiceNumberLTE applies the LTE predicate on the "invoice_number" field.
func InvoiceNumberLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceNumber, v))
}

// InvoiceNumberContains applies the Contains predicate on the "invoice_number" field.
func InvoiceNumberContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldInvoiceNumber, v))
}

// InvoiceNumberHasPrefix applies the HasPrefix predicate on the "invoice_number" field.
func InvoiceNumberHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldInvoiceNumber, v))
}

// InvoiceNumberHasSuffix applies the HasSuffix predicate on the "invoice_number" field.
func InvoiceNumberHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldInvoiceNumber, v))
}

// InvoiceNumberIsNil applies the IsNil predicate on the "invoice_number" field.
func InvoiceNumberIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldInvoiceNumber))
}

// InvoiceNumberNotNil applies the NotNil predicate on the "invoice_number" field.
func InvoiceNumberNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldInvoiceNumber))
}

// InvoiceNumberEqualFold applies the EqualFold predicate on the "invoice_number" field.
func InvoiceNumberEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldInvoiceNumber, v))
}

// InvoiceNumberContainsFold applies the ContainsFold predicate on the "invoice_number" field.
func InvoiceNumberContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldInvoiceNumber, v))
}

// InvoiceDateEQ applies the EQ predicate on the "invoice_date" field.
func InvoiceDateEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceDate, v))
}

// InvoiceDateNEQ applies the NEQ predicate on the "invoice_date" field.
func InvoiceDateNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceDate, v))
}

// InvoiceDateIn applies the In predicate on the "invoice_date" field.
func InvoiceDateIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceDate, vs...))
}

// InvoiceDateNotIn applies the NotIn predicate on the "invoice_date" field.
func InvoiceDateNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceDate, vs...))
}

// InvoiceDateGT applies the GT predicate on the "invoice_date" field.
func InvoiceDateGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceDate, v))
}

// InvoiceDateGTE applies the GTE predicate on the "invoice_date" field.
func InvoiceDateGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceDate, v))
}

// InvoiceDateLT applies the LT predicate on the "invoice_date" field.
func InvoiceDateLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceDate, v))
}

// InvoiceDateLTE applies the LTE predicate on the "invoice_date" field.
func InvoiceDateLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceDate, v))
}

// InvoiceDateIsNil applies the IsNil predicate on the "invoice_date" field.
func InvoiceDateIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldInvoiceDate))
}

// InvoiceDateNotNil applies the NotNil predicate on the "invoice_date" field.
func InvoiceDateNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldInvoiceDate))
}

// InvoiceAmountEQ applies the EQ predicate on the "invoice_amount" field.
func InvoiceAmountEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountNEQ applies the NEQ predicate on the "invoice_amount" field.
func InvoiceAmountNEQ(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldInvoiceAmount, v))
}

// InvoiceAmountIn applies the In predicate on the "invoice_amount" field.
func InvoiceAmountIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountNotIn applies the NotIn predicate on the "invoice_amount" field.
func InvoiceAmountNotIn(vs ...float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldInvoiceAmount, vs...))
}

// InvoiceAmountGT applies the GT predicate on the "invoice_amount" field.
func InvoiceAmountGT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldInvoiceAmount, v))
}

// InvoiceAmountGTE applies the GTE predicate on the "invoice_amount" field.
func InvoiceAmountGTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldInvoiceAmount, v))
}

// InvoiceAmountLT applies the LT predicate on the "invoice_amount" field.
func InvoiceAmountLT(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldInvoiceAmount, v))
}

// InvoiceAmountLTE applies the LTE predicate on the "invoice_amount" field.
func InvoiceAmountLTE(v float64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldInvoiceAmount, v))
}

// InvoiceAmountIsNil applies the IsNil predicate on the "invoice_amount" field.
func InvoiceAmountIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldInvoiceAmount))
}

// InvoiceAmountNotNil applies the NotNil predicate on the "invoice_amount" field.
func InvoiceAmountNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldInvoiceAmount))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldIssuedAt, v))
}

// IssuedAtIsNil applies the IsNil predicate on the "issued_at" field.
func IssuedAtIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldIssuedAt))
}

// IssuedAtNotNil applies the NotNil predicate on the "issued_at" field.
func IssuedAtNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldIssuedAt))
}

// IssuedByEQ applies the EQ predicate on the "issued_by" field.
func IssuedByEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldIssuedBy, v))
}

// IssuedByNEQ applies the NEQ predicate on the "issued_by" field.
func IssuedByNEQ(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldIssuedBy, v))
}

// IssuedByIn applies the In predicate on the "issued_by" field.
func IssuedByIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldIssuedBy, vs...))
}

// IssuedByNotIn applies the NotIn predicate on the "issued_by" field.
func IssuedByNotIn(vs ...int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldIssuedBy, vs...))
}

// IssuedByGT applies the GT predicate on the "issued_by" field.
func IssuedByGT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldIssuedBy, v))
}

// IssuedByGTE applies the GTE predicate on the "issued_by" field.
func IssuedByGTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldIssuedBy, v))
}

// IssuedByLT applies the LT predicate on the "issued_by" field.
func IssuedByLT(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldIssuedBy, v))
}

// IssuedByLTE applies the LTE predicate on the "issued_by" field.
func IssuedByLTE(v int64) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldIssuedBy, v))
}

// IssuedByIsNil applies the IsNil predicate on the "issued_by" field.
func IssuedByIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldIssuedBy))
}

// IssuedByNotNil applies the NotNil predicate on the "issued_by" field.
func IssuedByNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldIssuedBy))
}

// RejectReasonEQ applies the EQ predicate on the "reject_reason" field.
func RejectReasonEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldRejectReason, v))
}

// RejectReasonNEQ applies the NEQ predicate on the "reject_reason" field.
func RejectReasonNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldRejectReason, v))
}

// RejectReasonIn applies the In predicate on the "reject_reason" field.
func RejectReasonIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldRejectReason, vs...))
}

// RejectReasonNotIn applies the NotIn predicate on the "reject_reason" field.
func RejectReasonNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldRejectReason, vs...))
}

// RejectReasonGT applies the GT predicate on the "reject_reason" field.
func RejectReasonGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldRejectReason, v))
}

// RejectReasonGTE applies the GTE predicate on the "reject_reason" field.
func RejectReasonGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldRejectReason, v))
}

// RejectReasonLT applies the LT predicate on the "reject_reason" field.
func RejectReasonLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldRejectReason, v))
}

// RejectReasonLTE applies the LTE predicate on the "reject_reason" field.
func RejectReasonLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldRejectReason, v))
}

// RejectReasonContains applies the Contains predicate on the "reject_reason" field.
func RejectReasonContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldRejectReason, v))
}

// RejectReasonHasPrefix applies the HasPrefix predicate on the "reject_reason" field.
func RejectReasonHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldRejectReason, v))
}

// RejectReasonHasSuffix applies the HasSuffix predicate on the "reject_reason" field.
func RejectReasonHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldRejectReason, v))
}

// RejectReasonIsNil applies the IsNil predicate on the "reject_reason" field.
func RejectReasonIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldRejectReason))
}

// RejectReasonNotNil applies the NotNil predicate on the "reject_reason" field.
func RejectReasonNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldRejectReason))
}

// RejectReasonEqualFold applies the EqualFold predicate on the "reject_reason" field.
func RejectReasonEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldRejectReason, v))
}

// RejectReasonContainsFold applies the ContainsFold predicate on the "reject_reason" field.
func RejectReasonContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldRejectReason, v))
}

// EmailSentEQ applies the EQ predicate on the "email_sent" field.
func EmailSentEQ(v bool) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmailSent, v))
}

// EmailSentNEQ applies the NEQ predicate on the "email_sent" field.
func EmailSentNEQ(v bool) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldEmailSent, v))
}

// EmailErrorEQ applies the EQ predicate on the "email_error" field.
func EmailErrorEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEQ(FieldEmailError, v))
}

// EmailErrorNEQ applies the NEQ predicate on the "email_error" field.
func EmailErrorNEQ(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNEQ(FieldEmailError, v))
}

// EmailErrorIn applies the In predicate on the "email_error" field.
func EmailErrorIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIn(FieldEmailError, vs...))
}

// EmailErrorNotIn applies the NotIn predicate on the "email_error" field.
func EmailErrorNotIn(vs ...string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotIn(FieldEmailError, vs...))
}

// EmailErrorGT applies the GT predicate on the "email_error" field.
func EmailErrorGT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGT(FieldEmailError, v))
}

// EmailErrorGTE applies the GTE predicate on the "email_error" field.
func EmailErrorGTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldGTE(FieldEmailError, v))
}

// EmailErrorLT applies the LT predicate on the "email_error" field.
func EmailErrorLT(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLT(FieldEmailError, v))
}

// EmailErrorLTE applies the LTE predicate on the "email_error" field.
func EmailErrorLTE(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldLTE(FieldEmailError, v))
}

// EmailErrorContains applies the Contains predicate on the "email_error" field.
func EmailErrorContains(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContains(FieldEmailError, v))
}

// EmailErrorHasPrefix applies the HasPrefix predicate on the "email_error" field.
func EmailErrorHasPrefix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasPrefix(FieldEmailError, v))
}

// EmailErrorHasSuffix applies the HasSuffix predicate on the "email_error" field.
func EmailErrorHasSuffix(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldHasSuffix(FieldEmailError, v))
}

// EmailErrorIsNil applies the IsNil predicate on the "email_error" field.
func EmailErrorIsNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldIsNull(FieldEmailError))
}

// EmailErrorNotNil applies the NotNil predicate on the "email_error" field.
func EmailErrorNotNil() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldNotNull(FieldEmailError))
}

// EmailErrorEqualFold applies the EqualFold predicate on the "email_error" field.
func EmailErrorEqualFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldEqualFold(FieldEmailError, v))
}

// EmailErrorContainsFold applies the ContainsFold predicate on the "email_error" field.
func EmailErrorContainsFold(v string) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.FieldContainsFold(FieldEmailError, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.InvoiceRequest {
	return predicate.InvoiceRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceRequest) predicate.InvoiceRequest {
	return predicate.InvoiceRequest(sql.NotPredicates(p))
}
